- README.md
- cli/.changeset/chilly-hounds-pump.md
- cli/src/build.ts
The fewer steps, the better for the user.
> chore: remove unnecessary config step for user

- src/build.ts
> Fix server-function bundle structure when Next.js is inside a monorepo

- src/build.ts
> Add support for .cjs and .mjs next config

- src/build.ts
> Add support for Next.js "src" directory

- .changeset/plenty-beers-help.md
- packages/open-next/src/adapters/image-optimization-adapter.ts
- packages/open-next/src/adapters/server-adapter.ts
- packages/open-next/src/adapters/util.ts
> Set default NODE_ENV to production

- .changeset/kind-bananas-poke.md
- packages/open-next/src/adapters/event-mapper.ts
- packages/open-next/src/adapters/image-optimization-adapter.ts
- packages/open-next/src/adapters/server-adapter.ts
Add support for payload format v1 which is used by api gateway rest apis. 
This is still WIP, but I'm open to feedback on the approach.
> WIP support v1 format

- packages/open-next/src/build.ts
fixing the spelling of adapter, relies and determines
> fixing the spelling of adapter, relies and determines

- .changeset/six-vans-decide.md
- packages/open-next/src/adapters/next-types.ts
- packages/open-next/src/adapters/require-hooks.ts
- packages/open-next/src/adapters/server-adapter.ts
- packages/open-next/src/adapters/util.ts
This PR should fix: 
- Next overriding the needed react resolution override
- Fix `isApp` for:
- Group routes
- Index page (including index page under group routes)
> fix: group routes react resolution

- .changeset/fast-kangaroos-hang.md
- packages/open-next/src/adapters/cache.ts
Fix support for `notFound` and `redirect` in getStaticProps
> Fix isr not found

- .changeset/hip-drinks-explode.md
- .changeset/tame-papayas-change.md
- example/middleware.js
- example/package.json
- example/pages/middleware-rewrite-with-isr-destination.js
- example/pages/middleware-rewrite-with-isr.js
- example/pnpm-lock.yaml
- example/sst.config.ts
- packages/open-next/src/adapters/server-adapter.ts
this closes #142 
It also updates the example repo but maybe it should not be in that PR and is not strictly necessary
> fix ISR when used in addition to middleware rewrite

- .github/actions/pnpm-setup/action.yml
- .github/workflows/nextjs.yml
- .github/workflows/release.yml
Fixes wrong reference inside Github actions after changes made in #183
> ci(prettier): remove invalid prettier reference from pipeline

- examples/sst/sst.config.ts
- examples/sst/stacks/AppPagesRouter.ts
- package.json
Add `App + Pages Router` test
Add turbo script for e2e:test
> Fix e2e test setup

- packages/tests-e2e/tests/pagesRouter/isr.test.ts
- packages/tests-e2e/tests/pagesRouter/ssr.test.ts
> Revert "fix: e2e tests"

- packages/open-next/src/build.ts
> fix(sharp): escape path and simplify env setting

- README.md
- packages/open-next/src/adapters/cache.ts
- packages/open-next/src/build.ts
- packages/open-next/src/plugin.ts
- packages/tests-e2e/tests/appRouter/isr.revalidate.test.ts
This PR should fix fallback false issue.
It also fix a bug where the plugin system was not applied correctly, and added some log during plugin execution for better debugging
It should also remove all the key not found error in S3
> Fix falback

- examples/app-pages-router/middleware.ts
- examples/app-router/middleware.ts
- packages/open-next/src/adapters/routing/middleware.ts
- packages/tests-e2e/tests/appPagesRouter/middleware.redirect.test.ts
- packages/tests-e2e/tests/appRouter/middleware.redirect.test.ts
- packages/tests-unit/tsconfig.json
> fix: pass through headers on redirect

- packages/open-next/src/adapters/routing/matcher.ts
> Exclude manifest.json, robots.txt and sitemap.xml from routing matcher

- README.md
adds TUDN to who is using OpenNext
> Adds TUDN to who is using OpenNext

- examples/app-pages-router/next.config.js
- packages/open-next/src/adapters/routing/matcher.ts
- packages/open-next/src/adapters/types/next-types.ts
- packages/tests-e2e/tests/appPagesRouter/skip_trailing.test.ts
`skipTrailingSlashRedirect` from `next-config` was ignored
> fix skip trailing slash redirect

- docs/pages/v3/_meta.json
- docs/pages/v3/config.mdx
- docs/pages/v3/index.mdx
- docs/pages/v3/override.mdx
Just some docs for open-next V3 release candidate
> Initial docs for V3

- .changeset/pretty-spies-rush.md
- examples/app-pages-router/.env
- examples/app-pages-router/app/ssr/page.tsx
- examples/pages-router/.env.production
- examples/pages-router/src/pages/ssr/index.tsx
- packages/open-next/src/build/createServerBundle.ts
- packages/open-next/src/build/helper.ts
- packages/tests-e2e/tests/appPagesRouter/ssr.test.ts
- packages/tests-e2e/tests/pagesRouter/ssr.test.ts
> Fix env file not being copied in V3

- .changeset/early-parrots-think.md
- packages/open-next/src/core/routing/util.ts
- packages/open-next/src/http/openNextResponse.ts
> Add missing method from NextResponse for next 12

- .changeset/brave-eggs-end.md
- docs/pages/config/_meta.json
- docs/pages/config/nx.mdx
- packages/open-next/src/build.ts
- implements the solution in #468 by @jarodsim (and so fixes #468)
- adds documentation on how to use Open-next and SST within an Nx monorepo.
> fix: Nx monorepo support

- .changeset/shy-readers-tease.md
- packages/open-next/src/build.ts
next.js 15 has added typescript support for next.config.js. running create-next-app@canary with typescript now generates next.config.ts
- https://github.com/vercel/next.js/pull/67606
> support next.config.ts

- .changeset/cuddly-waves-smash.md
- examples/pages-router/next.config.js
- packages/open-next/src/core/routing/i18n/accept-header.ts
- packages/open-next/src/core/routing/i18n/index.ts
- packages/open-next/src/core/routing/matcher.ts
- packages/open-next/src/types/next-types.ts
- packages/tests-e2e/tests/pagesRouter/redirect.test.ts
> fix rewrite/redirect with i18n

- .changeset/chilled-eels-sort.md
- packages/open-next/package.json
- packages/open-next/src/plugins/edge.ts
- pnpm-lock.yaml
> fix missing polyfill URLPattern

- .changeset/lovely-penguins-taste.md
- packages/open-next/src/adapters/config/util.ts
- packages/open-next/src/core/routingHandler.ts
- packages/open-next/src/types/next-types.ts
> fix 404 when basePath is set

- .changeset/smart-bees-divide.md
- packages/open-next/src/build/edge/createEdgeBundle.ts
> fix __import_unsupported being undefined

- packages/open-next/src/build/generateOutput.ts
This PR fixes a small typo in #545.
> fix: typo in indexHandler constant

- .gitignore
- packages/tests-unit/vitest.config.ts
Example: https://github.com/opennextjs/opennextjs-aws/actions/runs/11346409364/job/31555398814#step:5:70
```
% Coverage report from v8
-------------------|---------|----------|---------|---------|-------------------
File               | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-------------------|---------|----------|---------|---------|-------------------
All files          |    3.73 |    47.24 |   22.83 |    3.73 |                   
open-next/src     |       0 |        0 |       0 |       0 |                   
build.ts         |       0 |        0 |       0 |       0 | 1-747             
index.ts         |       0 |        0 |       0 |       0 | 1-48              
logger.ts        |       0 |        0 |       0 |       0 | 1-16              
minimize-js.ts   | …
```
> Fix test coverage reporting

- packages/open-next/src/build/createAssets.ts
> fix: create the directory before copying the config

- packages/open-next/src/adapters/middleware.ts
- packages/open-next/src/build/createMiddleware.ts
- packages/open-next/src/converters/aws-cloudfront.ts
[`feat: createMiddleware reports middleware usage`](https://github.com/opennextjs/opennextjs-aws/commit/9856239928f7f2fd4c3adbe2b97f84bfcd08c70a) makes createMiddleware report if middleware is used.
The other commits contains smaller updates.
> A few minor updates

- .github/actions/test/action.yml
- .github/workflows/check.yml
- packages/tests-unit/vitest.config.ts
Example output: https://github.com/opennextjs/opennextjs-aws/actions/runs/11415198269#summary-31764988744
> Add unit test coverage reporting

- examples/shared/package.json
For ref : https://github.com/opennextjs/opennextjs-aws/actions/runs/11522037287
> fix workflow

- packages/open-next/src/adapters/logger.ts
Thanks for noticing @sommeeeer
> refactor: remove dead code

- packages/utils/src/index.ts
That was missed from #652 
/cc @sommeeeer
> fix(utils): fix the build

- examples/app-router/app/api/after/revalidate/route.ts
- examples/app-router/middleware.ts
- examples/app-router/next.config.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
React 19 is stable now. I have successfully deployed the `examples` apps and ran the e2e test. Should work fine.
> chore: bump react and next in catalog

- packages/tests-e2e/package.json
- pnpm-lock.yaml
Trying to fix e2e
see https://github.com/microsoft/playwright/issues/30368
> test: update playwright

- packages/open-next/src/build/helper.ts
adds support of the new non-binary lock file 
ref: https://bun.sh/docs/install/lockfile
> feat: support new bun lock file

- .changeset/lucky-actors-flash.md
- packages/open-next/src/overrides/wrappers/cloudflare-node.ts
ref: https://github.com/cloudflare/workers-sdk/issues/8004
> fix(cloudflare): PPR in wrangler dev

- .github/workflows/e2e.yml
fixes https://github.com/opennextjs/opennextjs-aws/issues/720
> fix the e2e CI workflow

- packages/tests-e2e/tests/appRouter/sse.test.ts
- packages/tests-e2e/tests/appRouter/ssr.test.ts
Removing outdated code comments in the app-router test files, for reference see the conversation here: https://github.com/opennextjs/opennextjs-cloudflare/pull/406
> chore: remove outdated and no-longer valid code comments

- .changeset/strong-bees-judge.md
- packages/open-next/src/build/constant.ts
- packages/open-next/src/build/copyTracedFiles.ts
Ensure the instrumentation trace file is properly copied and integrated.
> Fix instrumentation trace file handling

- packages/open-next/package.json
- packages/open-next/src/adapters/routing/middleware.ts
- packages/open-next/src/adapters/types/next-types.ts
This is a backport of #810 to OpenNext V2
> [V2] backport vulnerability fix

- .changeset/quiet-games-retire.md
- packages/open-next/src/overrides/converters/edge.ts
Fix multiple cookies for edge converter
> fix cookies-edge-response

- .changeset/orange-kids-sort.md
- packages/open-next/src/core/routing/cacheInterceptor.ts
> Fix incorrect status code being sent from interceptor
