opennextjs/opennextjs-aws

src/adapters/middleware-adapter.ts, src/adapters/server-adapter.ts
This PR fixes some issues:
1) Nextjs doesn't parse the body if it already exists on the request object: https://github.com/vercel/next.js/blob/canary/packages/next/src/server/api-utils/node.ts#L474
2) If a header has a space it in, the custom header ends up w/ `null` fields
3) `compress: false` has been fixed in the latest nextjs version.
EDIT: Do not merge yet
=> fix: delete request body from server adapter

README.md
Hey, what's up﻿?!
This fixes a typo in the quick start section of the readme
=> docs(readme): fix typo in quick start section

README.md, src/adapters/image-optimization-adapter.ts, src/adapters/middleware-adapter.ts, src/adapters/server-adapter.ts, src/build.ts, src/index.ts
This PR allows `next-auth/middleware` to properly run in Lambda environment.
When using this w/ NextjsSitev2 you will probably get infinite redirects due to the way the CloudFront Distribution is set up. To get around this, you can make changes to NextjsSite, eg:
NOTE: there's a limit of 25 cache behaviors, so if you need more than that just request a quota upgrade and you should easily get several hundred. 
```typescript
createCloudFrontDistributionForRegional() {
...
const baseServerBehavior = {
viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
origin: new origins.HttpOrigin(Fn.parseDomainName(fnUrl.url)),
allowedMethods: cloudfront.AllowedMethods.ALLOW_ALL,
cachedMethods: cloudfront.CachedMethods.CACHE_GET_HEAD_OPTIONS,
compress: true,
cachePolicy: …
```
=> fix: Fix next-auth middleware not working on Lambda

.changeset/spicy-moose-brush.md, packages/open-next/src/build.ts
This makes it possible to run open-next without a public folder created
=> open-next build no longer fail on missing public folder

.changeset/dirty-apricots-shout.md, README.md, packages/open-next/src/adapters/image-optimization-adapter.ts, packages/open-next/src/adapters/next-types.ts, packages/open-next/src/adapters/server-adapter.ts, packages/open-next/src/adapters/util.ts, packages/open-next/tsconfig.json
https://github.com/vercel/next.js/pull/49168/files#diff-7550a61853cf6a2d455d1613bd428eb42c6fc2057ce87e8ba7adab4094abcb6e
Next 13.1 and below had a bug where it would use the precompiled next library. 13.2+ fixes it so open-next needs to explicitly set the `NEXT_PRIVATE_PREBUNDLED_REACT` flat to `"next"`
=> fix: fix next not using prebundled react library

.changeset/polite-rice-learn.md, packages/open-next/src/adapters/response.ts
When using NextResponse in middleware, the Uint8Array instance type becomes corrupted in some way due to cross realm context????
eg:
```
return new NextResponse(JSON.stringify({})), {status: 200, headers: {'content-type': 'application/json'}})
```
The `data instanceof Uint8Array` returns false b/c the data traveled far across realms: middleware => server
per chatGPT:
```
The expression `uint8Array instanceof Uint8Array` can sometimes return `false` in JavaScript due to the way objects and prototypes work.
In JavaScript, the `instanceof` operator checks if an object is an instance of a specific constructor. It traverses the prototype chain of the object to determine if the object inherits from the specified constructor's prototype.
However, there are situations where the prototype chain …
```
=> fix: response throwing error due to javascript bug

.changeset/nervous-bananas-remember.md, packages/open-next/src/adapters/event-mapper.ts
Simply adds some checks that the fields exist before  attempting  to iterate over them with Object.entries
as requested in discord:
https://discord.com/channels/983865673656705025/1027265626085019769/1098297764359700500
=> fix: Safecheck Object.entries for APIGatewayProxyEventHeaders

.changeset/flat-monkeys-behave.md, packages/open-next/src/adapters/next-types.ts, packages/open-next/src/adapters/require-hooks.ts, packages/open-next/src/adapters/server-adapter.ts, packages/open-next/src/adapters/util.ts
This PR fix 2 issues:
- For users using monorepo without hoisting react at the root of the monorepo, `overrideDefault` was trying to resolve from the root
- `getMaybePagePath` has been replaced by some custom logic since it wasn't working for dynamic routes. (External dependencies could cause issue on these routes)
=> Fix react dependencies resolution

.changeset/tame-papayas-change.md, packages/open-next/src/adapters/server-adapter.ts
This PR should solve issue #138 the error happens when the page path is too long for the message MessageDeduplicationId
that needs to be less than 128 characters (see [documentation](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessage.html#API_SendMessage_RequestSyntax) )
I though about truncating the page path but if some pages share the same start of the (really long) path then we would get collisions on the message id potentially.
=> hash MessageDeduplicationId to avoid invalid values

.changeset/twenty-hounds-refuse.md, packages/open-next/src/adapters/response.ts
With the API function `pages/api/test.ts`:
``` ts
export default async function handler(req: NextApiRequest, res: NextApiResponse) {
res.status(405).setHeader('Allow', 'OPTIONS').end();
}
```
`GET /api/test` request should return `405 Method Not Allowed` HTTP response with `Allow: OPTIONS` header.
`next dev` works correctly  but compiled open-next server function returns `500 Internal Server Error`.
CloudWatch Logs says:
```
ERROR	TypeError: Cannot read properties of undefined (reading 'end')
at handler (/var/task/apps/front/.next/server/pages/api/test.js:84:51)
at /var/task/node_modules/next/dist/server/api-utils/node.js:463:16
at /var/task/node_modules/next/dist/server/lib/trace/tracer.js:117:36
at NoopContextManager.with (/var/task/node_modules/next/dist/compiled/@opentelemetry/api/inde …
```
=> NextApiResponse: setHeader() and writeHead() should return `this`

.changeset/clever-waves-know.md, packages/open-next/src/build.ts
For pages using `fallback:true`, we need to keep the html files. This PR fix this
=> fix: missing html files for non blocking fallback page

README.md
Adding a CDK framework forked from jetbridge/cdk-nextjs to support all other JSII languages. I needed to get it packaged for Java and thought others may benefit from it.
=> Additional framework for CDK with support for TS,Java,Go,Py,.NET

.changeset/moody-ways-knock.md, packages/open-next/src/adapters/require-hooks.ts
Should fix `Cannot find module /var/task/node_modules/react/jsx-runtime.js`
=> fix: missing react/jsx-runtime for require-hooks

.github/workflows/e2e.yml, examples/app-pages-router/next.config.js, examples/app-router/next.config.js, examples/pages-router/next.config.js, examples/pages-router/package.json, pnpm-lock.yaml
Removed the next.config.js output and tracing to see if that's necessary if we only build the `open-next` package.
=> Run e2e on main push

README.md, packages/open-next/package.json, packages/open-next/src/adapters/plugins/routing/default.ts, packages/open-next/src/adapters/plugins/routing/util.ts, packages/open-next/src/adapters/server-adapter.ts, packages/tests-unit/.gitignore, packages/tests-unit/tests/utils.test.ts, packages/utils/src/index.ts, pnpm-lock.yaml
server-adapter replaces `stale-while-revalidate` in Cache-Control header.
ref. https://github.com/serverless-stack/open-next#workaround-nextserver-does-not-set-correct-swr-cache-headers
When getServerSideProps sets correct swr, for example:
``` js
export const getServerSideProps = async ({ res }) => {
// fetch my data
res.setHeader('Cache-Control', 'max-age=60, stale-while-revalidate=86400');
return { props: /* my data */ }
};
```
server-adapter generates incorrect Cache-Control:
```
Cache-Control: max-age=60, stale-while-revalidate=2592000=86400
```
This PR fixes to prevent replacing `stale-while-revalidate=<duration>`.
Test:
```
> 'max-age=60, stale-while-revalidate'.replace(/\bstale-while-revalidate(?!=)/, "stale-while-revalidate=2592000")
'max-age=60, stale-while-revalidate=2592000'
> …
```
=> server-adapter: prevent to replace correct swr header

README.md, examples/app-router/middleware.ts, packages/open-next/src/adapters/plugins/routing/util.ts, packages/open-next/src/build.ts, packages/open-next/src/index.ts, packages/tests-e2e/tests/appRouter/isr.test.ts
This change introduces a custom `build-output-path` and `app-path` argument which makes it more flexible to support monorepo flavors with decentralised build options.
An example of such a monorepo is an [Nx integrated repository](https://nx.dev/getting-started/tutorials/integrated-repo-tutorial), where apps are placed under `apps/[appName]` and build artifacts are output to `dist/apps/[appName]`. This will allow you to build a more generic script which is being executed from the root of the monorepo.
Besides that a small change is included to also support single-version monorepos, where the `package.json` is exclusively maintained from the root of the monorepo.
These changes are made in a non-breakable manner, paths are being defaulted to the current `process.cwd()` just like before.
=> Introduce a custom build-output-path and app-path argument for more flexible monorepo support.

packages/open-next/src/adapters/event-mapper.ts
When there is no cookies on the headers in lambda@edge there will be an exception
=> fix for when there is no cookies lambda@edge

packages/open-next/src/adapters/plugins/routing/util.ts
Some of the headers are coming in as an array (need to investigate) but this should fix crashes some users are experiencing.
=> fix crash when headers is an array

examples/app-router/middleware.ts, packages/open-next/src/adapters/event-mapper.ts, packages/tests-e2e/tests/appRouter/middleware.cookies.test.ts
The API Gateway Proxy Result v2 expected the `cookies` to be a string array of the cookies. The next-server response `cookies.set` adds them as a single array of strings, delimited by a comma.
Issue: Cookies set in middleware was not being set in the response
Fix: Cookies are returned and set on the browser.
=> Fix: middleware cookies

packages/open-next/src/adapters/event-mapper.ts, packages/open-next/src/adapters/util.ts, packages/tests-unit/tests/adapter.utils.test.ts
2.1.3 included a fix that did a basic split on a comma, but that doesn't handle the case where the`Set-Cookie` includes: `Expire=Thu 01, Jan 1970...`
=> Fix cookie parse with "Expire="

README.md, examples/app-router/app/api/isr/route.ts, packages/open-next/src/adapters/plugins/routing/util.ts, packages/open-next/src/adapters/revalidate.ts, packages/tests-e2e/tests/appRouter/isr.revalidate.test.ts
Right now there is an issue with ISR due to the way a SQS FIFO Queue works.
SQS FIFO queue process revalidation page only one at a time for each messageGroupId. For website with a lot of ISR routes, there might be a backlog that will build up with time.
In order to solve this, we set the MessageGroupId of each SQS request like `revalidate-RANDOM_INT`.
This random int also need to always be the same for every unique path.
You could now set an env variable `MAX_REVALIDATE_CONCURRENCY` on the server function to specify the max number of simultaneous revalidate that you want. By default this env variable is set to 10.
=> feat: add support for multiple revalidation at once

packages/open-next/src/adapters/cache.ts, packages/open-next/src/adapters/server-adapter.ts, packages/open-next/src/build.ts, packages/open-next/src/index.ts
The incremental cache in nextjs is actually recreated on every request, everything inside the constructor of incremental cache is executed several times during the lifetime of a lambda.
This PR should solve several issues with incremental cache :
- An issue arise when the lambda stays alive long enough, you'll get a `EMFILE: too many open files` error. To solve this we replaced `loadBuildId` with `process.env.NEXT_BUILD_ID` and made s3Client and dynamoClient global to the lambda. It should solve this issue :crossed_fingers: 
- The dynamodb provider was not generated when there was no fetch cache, but if you don't use fetch cache but want to use `revalidatePath`, it would not have worked.
- There is 2 new flags, `--dangerously-disable-dynamodb-cache` and …
=> Fix : incremental cache fixes

examples/app-router/app/config-redirect/page.tsx, examples/app-router/next.config.js, packages/open-next/src/adapters/routing/matcher.ts, packages/tests-e2e/tests/appRouter/config.redirect.test.ts
When `cookie['key-does-not-exist-and-will-be-undefined']`, the cookie matcher logic would return `true` because `undefined !== ""`
See: `cookies?.[redirect.key] !== ""`
=> fix cookie redirect matcher

packages/open-next/src/build.ts
Update build.ts to allow environment variable driven override of the sharp version, which fixes #243
=> Allow sharp version override in build

examples/pages-router/next.config.js, packages/open-next/src/adapters/config/util.ts, packages/open-next/src/adapters/routing/matcher.ts, packages/open-next/src/adapters/types/next-types.ts, packages/tests-e2e/tests/pagesRouter/isr.test.ts, packages/tests-e2e/tests/pagesRouter/rewrite.test.ts, packages/tests-e2e/tests/pagesRouter/ssr.test.ts, packages/tests-e2e/tests/pagesRouter/trailing.test.ts
This PR solve issue with `trailingSlash` config in `next.config.js`. Fix #260 
It also solve an issue when people use `rewrites` config in `next.config.js` using array instead of the more complex 
```js
rewrites: () => ({
beforeFiles: [...],
afterFiles: [...],
...
})
```
=> Fix trailing slash

docs/pages/common_issues.mdx, docs/pages/common_issues/bundle_size.mdx, packages/tests-e2e/README.md
fixes: #166 
Edit: one of the changes breaks server actions 😢 
We might be better off removing the dev modules inside `build.ts`...
=> docs: add documentation on minimizing lambda bundle

packages/open-next/src/adapters/routing/matcher.ts, packages/tests-e2e/README.md, packages/tests-e2e/tests/appRouter/trailing.test.ts, packages/tests-e2e/tests/pagesRouter/trailing.test.ts
Fixes: https://github.com/sst/open-next/issues/279
=> TrailingSlash using rewrite for a fetch call results on infinite loop

README.md, packages/open-next/src/adapters/cache.ts, packages/open-next/src/adapters/constants.ts, packages/open-next/src/adapters/dynamo-provider.ts, packages/open-next/src/adapters/util.ts
For larger pre-rendered sites, throwing thousands of requests at DDB immediately overwhelms the throughput.
This change mitigates this.
=> Double chunk DDB batch writes to not overwhelm DDB on load

docs/pages/common_issues/bundle_size.mdx
update bundle size docs to show that outputFileTracingExcludes lives within the experimental next.config option
=> update bundle size docs to show that outputFileTracingExcludes lives in experimental

packages/open-next/src/build.ts
Fixes #158 
This PR adds functionality to check for the existence of favicon.ico in the `src/app/` or `app/` directory and, if present, copies it to the `.open-next/assets` directory.
=> fix: copy favicon.ico from app dir

packages/open-next/src/adapters/plugins/routing/default.replacement.ts, packages/open-next/src/adapters/plugins/routing/util.ts, packages/open-next/src/adapters/routing/middleware.ts, packages/open-next/src/adapters/routing/util.ts
This PR should fix a couple of external rewrite issue
=> Fix external rewrite

docs/pages/inner_workings/isr.mdx, packages/open-next/src/adapters/cache.ts, packages/open-next/src/build.ts
The goal of this PR is to reduce the number of S3 call that we need to make for the S3 incremental cache
Before this PR there was 1 `ListObjectsV2Command` and 2 to 3 `GetObjectCommand` for every `get` of the incremental cache, this has been reduced to a single `GetObjectCommand`
For the `set` part of the incremental cache, we go from 2-3 `PutObjectCommand` to a single one.
This also reduce the number of objects in the S3 cache
TODO:
=> Perf Reduce s3 calls

.changeset/lazy-pens-bake.md, packages/open-next/src/adapters/cache.ts, packages/open-next/src/adapters/plugins/routing/util.ts, packages/open-next/src/adapters/routing/middleware.ts
This PR aims to solve an issue regarding inconsistencies between rsc (or json) data and html data for ISR.
Until now next set the `cache-control` header to `s-maxage=X, stale-while-revalidate` with `X` being the revalidate value.
This cause inconsistencies between rsc and html data due to cdn caching especially for big revalidate value.
For example with `revalidate=3600`, rsc and html could be out of sync by a maximum of 3599 seconds. It is assuming someone accessed the html at `t=0` and no one accessed the rsc until `t=3599`. 
This behaviour is exacerbated with app dir since every `<Link />` pointing to the same route from a different route will result in a different rsc call and thus a different cdn cache entry.
This PR also fix the 5 min deduplication window of the SQS queue.
=> Fix swr client inconsistencies

packages/open-next/src/adapters/plugins/routing/util.ts
This is a minor fix on a crash, but needs investigation later.
I tried to pipe the request instead and it works for some sites...
Need to look into https://github.com/vercel/next.js/blob/canary/packages/next/src/server/lib/router-utils/proxy-request.ts
I tried creating the stream from the request but that didn't work 🤷
=> Fix getHeaders crash

packages/open-next/src/adapters/cache.ts
Right now the tag property is always empty, I tried to check in the nextjs code base the reason and i found [this relevant code](https://github.com/vercel/next.js/blob/b8b1ec24a259ac1a42a513971259bda62738dd47/packages/next/src/server/lib/patch-fetch.ts#L479C1-L498C18) 
this code was introduced in [this PR](https://github.com/vercel/next.js/commit/2eef7754728b3db8df8b1f52def0a47c8f0baed5#diff-4c54e369ddb9a2db1eed95fe1d678f94c8e82c540204475d42c78e49bf4f223a), So I'm wondering how we should manage that for older versions of nextjs that don't have that change.
Also ideally I would like to add some tests to the open-next repo to make sure that revalidateTag works ok but I still don't understand fully the setup and how to write that test so this PR is probably a WIP
=> fix: setting the right tag values for fetch cache

packages/open-next/src/build.ts, packages/open-next/src/index.ts
This PR addresses [this issue](https://github.com/sst/open-next/issues/296)  by adding a `--package-json` option to allow it to run with monorepos (In my specific case in a nx workspace).
=> Added --package-json option to specify package json path

examples/app-router/app/search-query/page.tsx, packages/open-next/src/adapters/event-mapper.ts, packages/open-next/src/adapters/routing/matcher.ts, packages/open-next/src/adapters/routing/middleware.ts, packages/open-next/src/adapters/routing/util.ts, packages/tests-e2e/tests/appRouter/query.test.ts, packages/tests-unit/tests/adapter.utils.test.ts, packages/tests-unit/tests/cache.test.ts
Changes querystrings with multi-value parameters from `"?key=value1,value2"` to `?key=value1&key=value2` since NextJS understands this format and converts it to an array when reading search params.
=> change querystring format for multi value parameters (#319)

.changeset/poor-ravens-attack.md, examples/app-pages-router/package.json, examples/app-router/app/api/revalidate-tag/route.ts, examples/app-router/app/revalidate-tag/layout.tsx, examples/app-router/app/revalidate-tag/nested/page.tsx, examples/app-router/app/revalidate-tag/page.tsx, examples/app-router/middleware.ts, examples/app-router/package.json, examples/pages-router/package.json, packages/open-next/src/adapters/cache.ts, packages/open-next/src/build.ts, packages/tests-e2e/tests/appRouter/revalidateTag.test.ts, pnpm-lock.yaml
This PR should fixes 2 issues from using `revalidateTag`
- A regression was introduced in #295 which made tags not being generated at build time for any route
- fetch cache is never read on next@14+, they changed the interface again
This PR also adds a test for `revalidateTag`
=> Fix tags cache

.changeset/wicked-comics-trade.md, packages/open-next/src/adapters/cache.ts, packages/open-next/src/build.ts
[Code generated icons](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons#generate-icons-using-code-js-ts-tsx) are cached as routes with a binary body. open-next currently merges the route meta and utf-8 encoded body into a single *.cache file, which can be problematic for binary png data. This PR simply changes the encoding on the cached route body from `utf8` to `base64` to preserve binary data.
Alternatively, we could preserve the utf-8 encoding on json routes, and only apply base64 when necessary according to `meta.headers.content-type`?
=> Changes encoding on cache.body from utf8 to base64

.changeset/afraid-ducks-speak.md, packages/open-next/src/adapters/routing/matcher.ts
Hi,
Current logic for matching headers does not 100% match how nextjs deals with it. For example when you have a `Content-Security-Policy` header which contains urls like `https://google.com` then the matching will fail resulting in an Internal Server Error.
This PR adds a small bandage so non matched headers are just returned as-is ensuring no Internal Server Error is triggered.
Ideally we have same logic as Nextjs
=> fix: try to match errors, fall back to just adding raw key / value pare

.changeset/moody-camels-help.md, packages/open-next/src/build.ts
This PR fixes the issue described in this issue #340 
By using the `import()` function the `process.env = ...` block runs first and the `CACHE_BUCKET_REGION` is defined.
I've published it to a personal organization (https://www.npmjs.com/package/@sstlv/open-next) and tested it in my project, it's working properly.
=> fix(open-next): use dynamic import handler for monorepo entrypoint

docs/pages/common_issues/bundle_size.mdx
The current fix didn't work, but this updated fix did work for me. Hence proposing this as another solution.
=> Update bundle_size.mdx for excluding pdfjs-dist optional dependency docs

.changeset/wet-brooms-cheer.md, packages/open-next/src/adapters/plugins/routing/util.ts
As the code reads in the comment right above the line I changed, NextServer will not respond with a cache-control header value for HTML pages.
Since the cache-control header value is never set upstream, open-next also never set its own cache-control header due to this truthy if check.
As HTML pages never got any cache-control value set, what should be some of the fastest pre-rendered pages actually become slower than SSR/ISR pages that do get a cache header set correctly. (In the case of `cdk-nextjs`, the value actually gets falls back to `no-cache`)
I tested this locally with a number of CloudFront events against a site with static HTML as well as other SSG/ISR page types and it helped a lot for static HTML pages. 🚀
=> fix(open-next): correctly set cache control for html pages

.changeset/tame-hotels-tell.md, packages/open-next/src/adapters/routing/matcher.ts, packages/tests-e2e/tests/appRouter/trailing.test.ts
Fix https://github.com/sst/open-next/issues/355
=> Fix trailing slash redirect to external domain

packages/open-next/src/build.ts
AWS Security Hub throws a HIGH-level severity finding on the image optimization lambda resource regarding the version of `sharp`.
Installed version: 0.32.5
Fixed version: 0.32.6
[GHSA-54xq-cgqr-rpm3](https://github.com/advisories/GHSA-54xq-cgqr-rpm3)
[CVE-2023-4863 - sharp](https://nvd.nist.gov/vuln/detail/CVE-2023-4863)
This PR bumps the installed version of [sharp](https://www.npmjs.com/package/sharp) in the build step to the minimum fixed version `0.32.6`, but if desired we can upgrade to the latest version at the time of writing `0.33.2`
=> security fix: upgrade sharp version to 0.32.6

packages/open-next/src/build.ts, packages/open-next/src/build/copyTracedFiles.ts, packages/open-next/src/build/createServerBundle.ts, packages/open-next/src/build/generateOutput.ts, packages/open-next/src/build/helper.ts
Happens when the `.open-next` folder does not exist.
Also includes a few trivial changes:
- Changed windows message to warning, since user can still continue
- Printing out a larger block of warning message and removed the 10s wait. Thinking being if it works for a windows user (miraculously), sucks having to wait 10s on each deploy.
- removed a few props from BuildOptions, that exists in both `config` and `options` that are being passed around.
=> Fix cannot write default config file b/c folder not created

.changeset/grumpy-students-smell.md, packages/open-next/src/adapters/routing/middleware.ts
=> fix: prevent duplication of location header

.changeset/short-eels-compare.md, packages/open-next/src/adapters/event-mapper.ts, packages/tests-unit/tests/event-mapper.test.ts
This PR parse the `set-cookie` header when converting the response to the CloudFront format.
`set-cookie: test=1; Path=/; HttpOnly; Secure; SameSite=None, test=2; Path=/; HttpOnly; Secure; SameSite=None`
`set-cookie: test=1; Path=/; HttpOnly; Secure; SameSite=None`
`set-cookie: test=2; Path=/; HttpOnly; Secure; SameSite=None`
I've published it to my own npm org and tested it in my application:
https://www.npmjs.com/package/@sstlv/open-next/v/2.3.7-beta.0
[#386]
=> fix(open-next): parse cookies when converting response to cloudfront

.changeset/small-knives-hug.md, packages/open-next/package.json, packages/open-next/src/adapters/event-mapper.ts, packages/tests-unit/tests/event-mapper.test.ts
This PR changes the CloudFront event mapper to remove blacklisted and read-only headers from the CloudFront response.
When a server action is called Next.js tries to set the Keep-alive header which it can't be provided in the CloudFront Lambda Edge.
That returns the following response
Status Code: 502
Response:
```log
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>502 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
The Lambda function result failed validation: The function tried to add a blacklisted header.
We can't connect to the server for …
```
=> fix(edge): remove read-only and blacklisted headers from cloudfront response

.changeset/hot-toys-push.md, packages/open-next/src/adapters/image-optimization-adapter.ts, packages/open-next/src/build.ts
At the moment, image from `_next/image` are only cached in the cdn.
We don't generate any `ETag` either for the image so we never get 304.
Every stale request actually needs to be recomputed again.
In order to improve perf and reduce cost, this PR introduces an env variable `OPENNEXT_STATIC_ETAG` that we can set on the image opt function.
When you set this env variable, we create an `ETag` that depends on some parameter that we know before performing the image opt: ( href, width, quality, buildId )
Stale request will then return a 304 for request where `if-none-match` header is equal to the computed `ETag`
**One important things to note**, when using this env variable, it means that all the images should be considered immutable (The source image should not change) and the only way to …
=> Feat add a static etag for Image

.changeset/blue-guests-punch.md, packages/open-next/src/adapters/plugins/routing/default.replacement.ts, packages/open-next/src/adapters/routing/matcher.ts
When requesting data for page dir with an incorrect `BUILD_ID`, we should return 404 with `{}` as the body.
This could cause some 500 on new deployment for page router, since running client could request data with the old `BUILD_ID`
Links to the discord thread : https://discord.com/channels/983865673656705025/1217895314741006387
=> Fix incorrect 200 with wrong buildId

.changeset/giant-pianos-float.md, packages/open-next/src/build.ts, packages/open-next/src/build/helper.ts
Fix #406 
Instead of checking `package.json` for next version, we do a `require.resolve` in the appPath directory to find the `package.json` of next. Then we require this package and check for the version there.
This should work every time
=> Fix next version check

.changeset/warm-waves-allow.md, packages/open-next/src/converters/aws-cloudfront.ts
Fix a bug introduced in rc-13.
We should not remove read only headers https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/edge-function-restrictions-all.html#function-restrictions-read-only-headers
=> Fix for external middleware

.changeset/fluffy-lamps-confess.md, examples/pages-router/next.config.js, packages/open-next/src/core/routing/matcher.ts, packages/open-next/src/core/routing/util.ts, packages/tests-e2e/tests/pagesRouter/rewrite.test.ts
Fix #263 
This PR fix the uses of named regex in next.config rewrites.
This one https://github.com/sst/open-next/issues/263#issuecomment-1832240508 works just fine now
=> Fix next rewrites

.changeset/brave-games-argue.md, packages/open-next/package.json, packages/open-next/src/converters/aws-apigw-v2.ts, packages/open-next/src/plugins/edge.ts
Some libs depends on crypto function or class that are available globally in the edge runtime, but are not present by default in node, this should fix it
=> Fix polyfill for crypto in the middleware 

.changeset/curly-points-remember.md, packages/open-next/package.json, packages/open-next/src/build/copyTracedFiles.ts
When using page router and static 404 and 500 ( i.e. no `getStaticProps` ) `open-next build` would fail because it cannot find the js file.
=> fix static 404 & 500 in page router

.changeset/chilled-horses-drum.md, packages/open-next/src/build.ts, packages/open-next/src/build/createServerBundle.ts, packages/open-next/src/types/open-next.ts
This patch adds support for running Open-next server functions with the [Deno lambda](https://github.com/denoland/deno-lambda) runtime layer.
Discussed briefly with @conico974 on Discord, adding `runtime: "deno"` made most sense.
- Compile a ES module version of `cache.ts` when runtime is set to "deno"
- Add a `deno.json` and rename function entrypoint as `index.ts` (this will be redundant with Deno 2)
- Import node globals in the entrypoint
Here's how a deployment config would look like:
```typescript
// open-next.config.ts
export default {
default: {
runtime: "deno"
}
}
```
```typescript
// sst.config.ts
export default $config({
app(input) {
return {
name: "my-app",
removal: input?.stage === "production" ? "retain" : "remove",
home: "aws",
};
},
async run() {
new sst.aws.Nextjs("MyWeb", …
```
=> Add support for 'deno' server functions

.changeset/orange-bees-lie.md, packages/open-next/src/build.ts, packages/open-next/src/build/compileConfig.ts, packages/open-next/src/build/createServerBundle.ts, packages/open-next/src/build/edge/createEdgeBundle.ts, packages/open-next/src/build/helper.ts, packages/open-next/src/index.ts, packages/open-next/src/types/open-next.ts
Before this PR, OpenNext used a single compiled `open-next.config.mjs` file even for the edge runtime. It achieved this by setting the platform as neutral in esbuild which caused a lot of trouble when using custom overrides.
With this PR OpenNext will create 2 different bundle for `open-next.config.mjs`, one for node and one for edge, and copy the correct one depending on the function runtime.
To properly support this, there is a new build args `--node-externals` that is used for esbuild during compilation of `open-next.config.ts` ( for example `--node-externals "@aws-sdk/*,sharp"` to remove every aws sdk and sharp deps from the config file ).
There is also a new options in `open-next.config.ts` : `edgeExternals` that serve the same purpose but for the edge version of …
=> Improve custom config support

docs/pages/index.mdx
Fix small typo in the "Who is using OpenNext?" section.
=> Fix small typo

.changeset/flat-coats-train.md, packages/open-next/src/converters/aws-cloudfront.ts
Fix #427 
This should fix the issue for lambda@edge deployed function.
We need to find a way to properly test this, maybe setting some proper unit test would be enough for most cases.
=> Fix for readonly headers lambda@edge

.changeset/tame-pets-juggle.md, packages/open-next/src/core/routing/util.ts, packages/open-next/src/core/routingHandler.ts, packages/tests-e2e/tests/pagesRouter/404.test.ts
When a request does not match any route at all, instead of returning the 404 page it returns a 500.
I'm pretty sure it does not happen on every version of next as well, something new that they added at one point.
It's an error in the next request handler itself (it tries to pipe to undefined), they must have moved this logic in the server router.
I need to add some e2e test for this as well.
=> fix 404 when no route match at all

packages/open-next/src/build/copyTracedFiles.ts
This fixes a bug that I encountered while deploying [this](https://github.com/andreia-oca/chatbot-ollama) application.
The problem is that the code uses a file from the `highlight.js` module called `csharp.js`. When I deploy the application built by open-next, I encounter the following error at runtime: `Cannot find module 'highlight.js/lib/languages/csharp'`.
I found that the reason for this error is an early return from `copyTracedFiles.ts`, which is falsely skipping the file `.next/standalone/node_modules/highlight.js/lib/languages/csharp.js`.
The solution that I propose is to skip if the path contains "node_modules/sharp" and "node_modules/canius-lite".
=> Fix for incorrect filter logic when copying traced files

.changeset/small-rivers-taste.md, packages/open-next/src/adapters/cache.ts, packages/open-next/src/adapters/server-adapter.ts, packages/open-next/src/cache/tag/dynamodb-lite.ts, packages/open-next/src/core/createMainHandler.ts, packages/open-next/src/core/requestHandler.ts, packages/open-next/src/core/routing/util.ts, packages/open-next/src/utils/fetch.ts, packages/open-next/src/utils/promise.ts
Latest releases introduced multiple *-lite that replaced aws-sdk with aws4fetch. This introduced some bug and uncover some underlying issues with the incremental cache itself.
This PR fixes : 
- S3 cache NoSuchKey error will now always be in debug
- For some reasons, fetch (even with `next:internal` and an authorization header) sometimes will still uses the fetch cache for aws4fetch call. There is now a `globalThis.internalFetch` that we can use that is set at start to normal fetch.
- A weird `SocketError: other side closed` can happen when not reading the body ( which was the case for some aws call )
And the BIG one: 
Cache set to S3 and sending to SQS were not properly awaited. Next itself doesn't seem to wait for cache set to be done before returning the response. 
This has been …
=> Fix some cache issue

.changeset/eight-parrots-peel.md, .eslintrc.cjs, docs/next.config.js, example/next.config.js, examples/app-pages-router/next.config.js, examples/app-router/app/api/sse/route.ts, examples/app-router/next.config.js, examples/pages-router/next.config.js, packages/open-next/src/adapters/cache.ts, packages/open-next/src/build.ts, packages/open-next/src/build/createServerBundle.ts, packages/open-next/src/core/createMainHandler.ts, packages/open-next/src/core/requestHandler.ts, packages/open-next/src/core/routing/util.ts, packages/open-next/src/http/openNextResponse.ts, packages/open-next/src/index.ts, packages/open-next/src/utils/promise.ts, packages/tests-e2e/tests/appPagesRouter/pages_ssr.test.ts, packages/tests-e2e/tests/appPagesRouter/ssr.test.ts, packages/tests-e2e/tests/appRouter/headers.test.ts, packages/tests-e2e/tests/appRouter/ssr.test.ts, packages/tests-e2e/tests/pagesRouter/ssr.test.ts, tsconfig.eslint.json
Don't know how this one could have gone undetected, but set is not properly awaited.
I'll test this and merge this tomorrow, probably do a release as well. 
Maybe the latest PR was not even entirely necessary
=> Fix: await cache set

packages/open-next/src/core/routing/middleware.ts
I've noticed that the response returned by the _next/data/.../middleware-geolocation.json endpoint is an entire HTML page instead of a JSON containing the props. I've also deployed the same app on Vercel and it responds with a JSON.
After a discussion with @conico974 on Discord, we came up with this fix.
=> Pass __nextDataReq in the middleware query params if already present

packages/open-next/src/http/openNextResponse.ts
This pull request fixes an issue where the middlewares were not functioning properly with the combination of versions specified below. Specifically, the "Middleware — redirect" functionality was failing to work as expected.
SST v2.43.2
Next.js version : 13.4.12
OpenNext v3.0.2
The error was the following:
```
TypeError: res.send is not a function
at Object.fn (/var/task/node_modules/next/dist/server/next-server.js:1933:33)
at async Router.execute (/var/task/node_modules/next/dist/server/router.js:315:32)
at async NextNodeServer.runImpl (/var/task/node_modules/next/dist/server/base-server.js:624:29)
at async NextNodeServer.handleRequestImpl (/var/task/node_modules/next/dist/server/base-server.js:549:20)
```
The implementation adds the missing methods used by next.
=> Implement missing methods from response object to fix the middleware issue in next 14.4.12 or lower.

.changeset/wicked-ligers-speak.md, packages/open-next/src/adapters/image-optimization-adapter.ts, packages/open-next/src/adapters/middleware.ts, packages/open-next/src/adapters/plugins/without-routing/requestHandler.ts, packages/open-next/src/build.ts, packages/open-next/src/converters/edge.ts, packages/open-next/src/core/requestHandler.ts, packages/open-next/src/core/resolve.ts, packages/open-next/src/core/routing/matcher.ts, packages/open-next/src/core/routingHandler.ts, packages/open-next/src/http/openNextResponse.ts, packages/open-next/src/overrides/imageLoader/host.ts, packages/open-next/src/overrides/imageLoader/s3.ts, packages/open-next/src/plugins/resolve.ts, packages/open-next/src/types/open-next.ts, packages/open-next/src/wrappers/cloudflare.ts
This PR fixes a few issues that happened when trying to use the external middleware with cloudflare.
=> Better support for cloudflare external middleware

.changeset/witty-dots-film.md, packages/open-next/src/build.ts
On Windows, if the file protocol is not specified when using dynamic imports, the process exits with `ERR_UNSUPPORTED_ESM_URL_SCHEME` error.
Full error:
```
node:internal/modules/esm/load:236
throw new ERR_UNSUPPORTED_ESM_URL_SCHEME(parsed, schemes);
^
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:236:11)
at defaultLoad (node:internal/modules/esm/load:128:3)
at ModuleLoader.load (node:internal/modules/esm/loader:409:13)
at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:56)
at new ModuleJob (node:internal/modules/esm/module_job:65:26)
at …
```
=> [windows] Specify the `file://` protocol when importing config on Windows

.changeset/popular-kids-beam.md, packages/open-next/src/plugins/resolve.ts
Previously, the separator for the filter regex was hardcoded to `/` (Unix separator).
Now, we're also taking account for the `\` (Windows separator) in the filter regex.
=> [windows] Add Windows compatibility for the `resolve` ESBuild plugin

.changeset/shy-cups-notice.md, packages/open-next/src/build.ts, packages/open-next/src/build/createServerBundle.ts
Previously, the separator for the filter regex was hardcoded to `/` (Unix separator).
Now, we're also taking account for the `\` (Windows separator) in the filter regex.
=> [windows] Add Windows compatibility for the `replacement` ESBuild plugin

.changeset/gold-paws-laugh.md, examples/app-router/app/api/revalidate-path/route.ts, examples/app-router/app/revalidate-path/page.tsx, examples/app-router/middleware.ts, packages/open-next/src/adapters/cache.ts, packages/open-next/src/cache/tag/dynamodb-lite.ts, packages/open-next/src/cache/tag/dynamodb.ts, packages/tests-e2e/tests/appRouter/revalidateTag.test.ts
- Fix `revalidateTag` for next 15+
- Fix `revalidatePath` not clearing the fetch cache ( When doing a `revalidatePath('/whatever')`, all the `fetch` or `unstable_cache` inside this route would return the cached value instead of refetching )
There is a few things that we need to think about:
Right now the fetch cache in OpenNext works in a different way than in `next start` to take full advantage of DynamoDB.
In `next start` for every get to the incremental cache, they check for every tag used in this get ( and this include layout, page and fetch cache tags ), we only check given the path which entry in DDB is newer, and if so consider the cache entry stale.  This mean we can make one single optimized query to DDB instead of either multiple get or an expensive scan/query.
On the other hand …
=> Fix issues with revalidateTag/revalidatePath

.changeset/angry-fans-kick.md, packages/open-next/src/build/edge/createEdgeBundle.ts
Middleware in the latest canary version of next are crashing with this error `Cannot redefine property: __import_unsupported`.
This PR fix it
=> fix middleware for next 15

.changeset/lucky-ravens-teach.md, packages/open-next/src/types/aws-lambda.ts, packages/open-next/src/wrappers/aws-lambda-streaming.ts
It looks like aws has made an update again to how the runtime works when using streaming.
Now even after `end()` has been called on the stream and the handler returned, the lambda keeps running in the background doing nothing until it timeout (and you'll be billed for the full duration)
This should fix it.
=> fix lambda streaming hanging after return

.changeset/lucky-dots-obey.md, packages/open-next/src/adapters/edge-adapter.ts, packages/open-next/src/adapters/image-optimization-adapter.ts, packages/open-next/src/converters/aws-apigw-v1.ts, packages/open-next/src/converters/aws-apigw-v2.ts, packages/open-next/src/converters/aws-cloudfront.ts, packages/open-next/src/converters/edge.ts, packages/open-next/src/converters/node.ts, packages/open-next/src/core/requestHandler.ts, packages/open-next/src/core/routing/matcher.ts, packages/open-next/src/core/routing/middleware.ts, packages/open-next/src/core/routing/util.ts, packages/open-next/src/types/open-next.ts, packages/open-next/src/utils/stream.ts, packages/open-next/src/wrappers/aws-lambda-streaming.ts, packages/open-next/src/wrappers/aws-lambda.ts
This PR change the body of `InternalResult` from `string` to `ReadableStream`.
This allow for edge runtime function to use streaming, and it is necessary to prepare for PPR.
This should also remove the need to add a `fakeStream` in non streaming wrapper as the stream is now always consumed if you return a body.
=> Feat readable body

.changeset/perfect-wasps-walk.md, examples/app-pages-router/open-next.config.ts, packages/open-next/src/adapters/middleware.ts, packages/open-next/src/build.ts, packages/open-next/src/build/edge/createEdgeBundle.ts, packages/open-next/src/cache/incremental/types.ts, packages/open-next/src/core/createMainHandler.ts, packages/open-next/src/core/routing/cacheInterceptor.ts, packages/open-next/src/core/routing/util.ts, packages/open-next/src/core/routingHandler.ts, packages/open-next/src/plugins/edge.ts, packages/open-next/src/types/next-types.ts, packages/open-next/src/types/open-next.ts, packages/tests-e2e/tests/appRouter/revalidateTag.test.ts
This PR allow the ISR/SSG cache to resolve before reaching `NextServer`.
This has 2 big benefits: 
- It reduces cold start because we don't need to load the js for the route for ISR/SSG ( It could have a big impact for path that match multiple route )
- It allows the cache hit to happen directly inside the external middleware ( This will allow us to make PPR works as intended inside the CDN and not in the server as in standalone mode)
This one probably need to be a Minor release as it will require some changes to the IAC ( external middleware will need extra permissions )
It is still WIP : 
Some notes around PPR : 
We probably want next to settle on an implementation, because as of right now there is no way to do it outside of minimal mode.
There is a dirty solution for this, we could …
=> Feat external cache

docs/pages/config/simple_example.mdx, docs/pages/inner_workings/_meta.json, docs/pages/inner_workings/cache_interception.mdx, docs/pages/inner_workings/routing.mdx
Add some docs for the new Cache Interception feature.
Also added some docs around routing in OpenNext and some docs on how to run as a classic Node server.
=> docs for 3.1

.changeset/tame-foxes-compete.md, packages/open-next/src/adapters/cache.ts, packages/open-next/src/build.ts
When creating new ISR page at runtime, inserted tags would make the fetch cache stale.
This will also fix cache miss when deploying using the same prebuilt data (i.e. not running `next build` again)
Fix #493
=> fix issue with fetch cache for new page

.changeset/silly-hounds-admire.md, packages/open-next/src/core/routing/middleware.ts
=> fix wrong locale in middleware

.changeset/mighty-elephants-design.md, packages/open-next/src/build/copyTracedFiles.ts, packages/open-next/src/build/patch/patchedAsyncStorage.ts, packages/open-next/src/core/createMainHandler.ts, packages/open-next/src/core/patchAsyncStorage.ts, packages/open-next/src/core/requestHandler.ts
ISR request are treated as On demand revalidation by Next, and it makes the fetch data cache not work as expected (the fetch cache is bypassed for every ISR revalidation request)
Should fix #493 
I'm not a very big fan of this solution but we either do that or patch some files in Next code itself and it's probably even worse.
=> patch asyncStorage for ISR and fetch

.changeset/fifty-clocks-report.md, examples/pages-router/next.config.js, examples/pages-router/src/middleware.ts, packages/open-next/src/core/routing/matcher.ts, packages/open-next/src/core/routing/middleware.ts, packages/tests-e2e/tests/pagesRouter/i18n.test.ts
This PR fix the matcher not working for the default locale in `headers` from `next.config` and the matcher from the middleware
Fix #516
=> fix matcher not working with i18n

.changeset/tasty-cherries-sort.md, packages/open-next/src/adapters/cache.ts, packages/open-next/src/build.ts
=> fix cache for next 15

.changeset/good-radios-sleep.md, packages/open-next/src/build/copyTracedFiles.ts, packages/open-next/src/build/validateConfig.ts
This PR improve `open-next.config.ts` file validation so that it's easier to understand what's wrong.
It also provides a better error when a route cannot be found for function splitting.
=> Improve config validation

.changeset/sixty-parents-stare.md, package.json, packages/open-next/package.json, pnpm-lock.yaml
Updates `path-to-regexp` to resolve https://github.com/advisories/GHSA-9wv6-86v2-598j
=> Update vulnerable path-to-regexp dependency

.changeset/dull-lobsters-hope.md, packages/open-next/src/cache/incremental/s3-lite.ts, packages/open-next/src/cache/tag/dynamodb-lite.ts, packages/open-next/src/queue/sqs-lite.ts
In some cases the env variable are not populated at import time, this make the lite client being able to handle this.
This also allow for some other use cases such as being able to use different region or different table/bucket/queue, by defining these env variable at runtime.
=> lazily initialize lite client

.changeset/weak-hotels-thank.md, packages/open-next/src/build.ts, packages/open-next/src/build/createServerBundle.ts, packages/open-next/src/build/edge/createEdgeBundle.ts, packages/open-next/src/core/createMainHandler.ts, packages/open-next/src/core/requestHandler.ts, packages/open-next/src/http/openNextResponse.ts, packages/open-next/src/plugins/edge.ts, packages/open-next/src/types/open-next.ts, packages/open-next/src/wrappers/aws-lambda-streaming.ts, packages/open-next/src/wrappers/cloudflare.ts, packages/open-next/src/wrappers/node.ts
This PR fix an issue with cloudflare env variable being undefined if the middleware does not run.
This was breaking `enableCacheInterception` with the middleware in cloudflare.
This PR also fix some issue with cookies being not properly set when set both in the routing layer (i.e. middleware or next.config) and the route itself.
It also fix an issue with cookies and the `node` wrapper
=> Fix cloudflare env

.changeset/polite-news-happen.md, packages/open-next/src/core/routingHandler.ts
Fixes: #522
I've verified changes locally but I couldn't find a way to easily include unit tests for this change. Please let me know if there are any additional changes you'd like me to make.
=> fix: fix basePath support for API routes

.changeset/mjwbenton.md, packages/open-next/src/core/routing/util.ts
As discussed on Discord here: https://discord.com/channels/1283128968140161065/1286094576788177059/1291327268450467893
Using rewrites with an external server currently has an issue when the server responds with a compressed response. `proxyRequest` decompresses the response, and suitably filters out the `content-encoding` header from the response to indicate that it is not compressed. However currently it still passes through the `content-length` header untouched. This means that downstream the response gets truncated to the length of the compressed response even though a decompressed response is being sent.
This PR filters out the optional `content-length` header such that the content does not get truncated.
Thanks!
=> fix content-length incorrectly set in proxyRequest

.changeset/aggregate.mjs, .changeset/config.json
This should fix release.
I also changed the changelog so that it use `@changesets/changelog-github`. This should automatically add a thanks  with the username and a link to their github. 
Hopefully this doesn't break anything ( It should have a `GITHUB-TOKEN` so it should be fine )
=> Fix release

docs/pages/index.mdx, docs/pages/inner_workings/components/server/node.mdx, docs/pages/v2.mdx, docs/pages/v2/common_issues/bundle_size.mdx, docs/theme.config.jsx, packages/open-next/package.json, packages/open-next/src/build/createServerBundle.ts
I've noticed that in a few places the repo base is outdated
this seems generally fine as github just redirects to this repository, but it's not really that polished and can break tools such as `pkg.pr.new` that can rely on the package.json's repository to be correct (see https://github.com/opennextjs/opennextjs-aws/pull/536#issuecomment-2403509138, the PR package there doesn't work properly because of the incorrect repo in the package.json)
=> update opennextjs-aws repository base

.eslintrc.cjs, examples/app-pages-router/middleware.ts, examples/app-router/middleware.ts
I've noticed that every PR is getting eslint warnings coming from the `examples` directory, so I figured I could open a quick PR to address them 🙂 
For example: https://github.com/opennextjs/opennextjs-aws/pull/543/files
=> fix all the various examples eslint warnings

.eslintrc.cjs, packages/open-next/src/adapters/cache.ts, packages/open-next/src/adapters/plugins/without-routing/requestHandler.ts, packages/open-next/src/build/copyTracedFiles.ts, packages/open-next/src/build/generateOutput.ts, packages/open-next/src/core/routing/i18n/accept-header.ts, packages/open-next/src/core/routingHandler.ts, packages/open-next/src/index.ts, packages/open-next/src/minimize-js.ts, packages/open-next/src/plugins/edge.ts
continuation from #544 🙂 
Some changes might be controversial I am happy to adjust them any way you prefer, I just applied what I thought more sensible and/or my personal preference 🙂
=> fix all the remaining eslint warnings

packages/open-next/src/build.ts, packages/open-next/src/build/createServerBundle.ts, packages/open-next/src/build/generateOutput.ts, packages/open-next/src/build/helper.ts
We (opennext-cloudflare) plan to reuse code from opennext-aws.
For that we would like to extract code out of `build.ts` so that we can call those functions from our own `build.ts`.
As a first step, this PR explicit function dependencies.
The PR contains multiple commits to ease the review.
=> Make function dependencies explicit

.changeset/green-insects-roll.md, packages/open-next/src/core/routing/util.ts
Currently if a request with the Accept-Encoding head is proxied e.g. with NextJs rewrites the response resolves before the full response has been processed.
=> fix: proxy resolves once the full stream has been completed.

.changeset/giant-vans-shop.md, examples/pages-router/next.config.js, packages/open-next/.changeset/tame-taxis-buy.md, packages/open-next/src/core/routing/util.ts, packages/open-next/src/types/next-types.ts, packages/tests-e2e/tests/appRouter/headers.test.ts, packages/tests-e2e/tests/pagesRouter/header.test.ts
=> feat: hide x-opennext header from server requests when poweredByHeader is false 

packages/tests-unit/tests/core/routing/matcher.test.ts
I haven't included tests for `handleFallbackFalse` because I don't feel like I understand the expected behaviour well enough.
=> Add unit tests for route matching

README.md
This PR is to fix the features list. The `Almost no coldstart` element.
=> fix: readme features list 

.github/actions/pnpm-setup/action.yml, .github/workflows/check.yml, .github/workflows/e2e.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml
> The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3, actions/setup-node@v3, pnpm/action-setup@v2, actions/cache@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
=> Fix github actions warnings for node20

.changeset/chilled-frogs-draw.md, packages/open-next/src/build/compileTagCacheProvider.ts, packages/open-next/src/build/createImageOptimizationBundle.ts, packages/open-next/src/build/createMiddleware.ts, packages/open-next/src/build/createRevalidationBundle.ts, packages/open-next/src/build/createServerBundle.ts, packages/open-next/src/build/createWarmerBundle.ts, packages/open-next/src/build/installDeps.ts, packages/open-next/src/types/open-next.ts
This PR fix #571 
In any of the function in `open-next.config.ts` you can now add a new option that will install dependencies that may not be included (For example sharp): 
```ts
install : {
packages: ["sharp@0.33"],
arch: "x64", // or arm64
nodeVersion: "18", // or 20 or 22
libc: "glibc" // or musl
}
```
Install itself is optional, and everything in it is optional besides packages
=> New option to install packages

.changeset/giant-horses-sin.md, packages/open-next/src/core/routing/i18n/index.ts, packages/open-next/src/types/next-types.ts, packages/tests-unit/tests/core/routing/i18n.test.ts
Hey there,
We found that the locale detection is forced and doesn't support the option `localeDetection` to `false` as linked below:
https://nextjs.org/docs/pages/building-your-application/routing/internationalization#disabling-automatic-locale-detection
Since it's an opt-out option, I forced the exact check with `false`
Thanks!
=> Support i18n localeDetection with value false

packages/open-next/src/core/routing/util.ts, packages/open-next/src/http/openNextResponse.ts
It seems that sometimes the 500 error page gets cached for some reason.
We don't want that to happen.
Update: 
This can happen for page router if your 500 (or 404) page use `getStaticProps`. 
For every route in page router that throws an exception, the cache-control gets overwritten and set as if it was an SSG route. The problem is that it doesn't remove the previous header that was set (including set-cookie). This could lead to session leakage.
Haven't tested in Next 15, this is probably fixed there since they don't override your cache-control anymore ( It might still happen if you don't set any cache-control for the route )
I added an env variable `OPEN_NEXT_DANGEROUSLY_SET_ERROR_HEADERS` that if set to true will disable the cache-control override that we do
=> fix 500 error page being cached

.changeset/honest-keys-protect.md, packages/open-next/src/adapters/binary.ts, packages/utils/src/binary.ts
Came across an issue where `open-next` seems to be encoding `application/x-protobuf` in utf8 corrupting the binary.
=> Add protobuf to common binary formats

examples/app-router/app/revalidate-path/page.tsx, packages/tests-e2e/tests/appRouter/revalidateTag.test.ts
This PR adds more reliable sources to the fetches in `revalidateTag.test.ts` e2e
=> fix: add more reliable sources to the revalidate e2e test

packages/open-next/src/build/compileConfig.ts, packages/open-next/src/build/copyTracedFiles.ts, packages/open-next/src/core/createGenericHandler.ts, packages/open-next/src/core/createMainHandler.ts, packages/open-next/src/overrides/wrappers/cloudflare.ts, packages/open-next/src/plugins/edge.ts, packages/open-next/src/plugins/replacement.ts
Those are all minor edits.
We can merge all/some/none.
=> refactor: minor cleanup

packages/tests-e2e/package.json, packages/tests-e2e/tests/appPagesRouter/isr.test.ts, packages/tests-e2e/tests/appPagesRouter/pages_isr.test.ts, packages/tests-e2e/tests/appPagesRouter/pages_ssr.test.ts, packages/tests-e2e/tests/appPagesRouter/ssr.test.ts, packages/tests-e2e/tests/appRouter/isr.test.ts, packages/tests-e2e/tests/appRouter/sse.test.ts, packages/tests-e2e/tests/appRouter/ssr.test.ts, packages/tests-e2e/tests/pagesRouter/isr.test.ts, packages/tests-e2e/tests/pagesRouter/ssr.test.ts, packages/tests-e2e/tests/utils.ts, packages/tests-unit/package.json, packages/tests-unit/tests/binary.test.ts, pnpm-lock.yaml
For some reason, pnpm doesn't seem to want to make `@open-next/utils` work anymore.
Since it's barely used at the moment, i just removed it from deps everywhere.
=> remove any deps to @open-next/utils

packages/open-next/src/core/routing/middleware.ts, packages/tests-unit/tests/core/routing/middleware.test.ts, packages/tests-unit/tests/core/routing/util.test.ts
The middleware handler default to https and it's causing troubles with the cloudflare dev server (wrangler dev) which uses http by default.
It is possible to force wrangler dev to use https (--local-protocol https) but the browser then shows a warning because the dev certificate is not secure.
=> fix(middleware): respect host protocol

.changeset/fluffy-peas-live.md, packages/open-next/src/overrides/converters/edge.ts
This is a temporary "hack" for the cloudflare adapter.
Why we need this:
- It is not possible to fetch a worker in the same zone
- Our first implementation will bundle the middleware and the server in a single worker
We will work on a better architecture later but this will unblock cloudflare for now and does not add overhead/code to the current edge converter. The alternative would be to fork the edge converter but it would be harder to keep the implemenations in sync.
=> feature(edge): add a way for convertTo to return a Request

.changeset/yellow-phones-juggle.md, packages/open-next/src/build/createMiddleware.ts
This is the second (and last) hack required for the middleware bundle on cloudflare.
For us the second build pass is hanlded by wrangler. This PR adds an option to disable that pass.
=> feat(middleware): add ability to force single build pass

packages/open-next/src/build/createImageOptimizationBundle.ts, packages/open-next/src/build/installDeps.ts, packages/open-next/src/types/open-next.ts
For some libs it seems that the default args that we used doesn't work, we can make all of them optional
=> Don't force args for install

.changeset/fuzzy-camels-check.md, packages/open-next/src/core/routing/matcher.ts, packages/open-next/src/core/routing/util.ts, packages/tests-unit/tests/core/routing/matcher.test.ts, packages/tests-unit/tests/core/routing/util.test.ts
=> Fix external redirect trailing

.changeset/sour-points-bake.md, examples/app-router/app/ssr/page.tsx, packages/open-next/src/adapters/cache.ts, packages/tests-e2e/tests/appRouter/ssr.test.ts
They changed the options again, fetchCache were never hit, it would be set but never read
=> fix fetch cache for next 15

.github/workflows/pre-release.yml, README.md
> [!note]
> this PR is matching what I am doing here: https://github.com/opennextjs/opennextjs-cloudflare/pull/115
> (I'm not sure if we also want an `experimental` branch here too?)
=> add main and experimental prereleases

packages/open-next/src/build/createMiddleware.ts, packages/open-next/src/build/edge/createEdgeBundle.ts, packages/open-next/src/plugins/edge.ts, packages/open-next/src/plugins/replacement.ts, packages/open-next/src/plugins/resolve.ts
=> fix: make plugins logs consistent

packages/open-next/src/core/createGenericHandler.ts, packages/open-next/src/core/createMainHandler.ts
This will help with Cloudflare were paths are resolved at build time.
Tested in both flat and monorepo setup.
=> use a literal path to import the config

packages/open-next/src/overrides/wrappers/cloudflare.ts
Use the code rather than the fullname.
See https://vercel.com/guides/geo-ip-headers-geolocation-vercel-functions#geolocation-headers
_(cloudfront correctly uses `cloudfront-viewer-region` vs `cloudfront-viewer-region-name`)_
=> fix: cloudflare geolocation

.changeset/tender-chicken-deliver.md, packages/open-next/src/build/createAssets.ts
In the case a Next.js application has a route handler for the `favicon.ico` path, we need to check to see if it's a file before copying it over to the output directory.
Example:
```ts
// /app/favicon.ico/route.ts
export const GET = async () => {
const favicon = await fetch('https://somecms.com').then((res) => res.arrayBuffer());
return new Response(favicon, {
headers: {
'Content-Type': 'image/x-icon',
},
});
};
export const dynamic = 'force-static';
```
=> fix(assets): check if favicon.ico is a file

.changeset/strong-keys-ring.md, packages/open-next/src/adapters/middleware.ts, packages/open-next/src/build/createMiddleware.ts, packages/open-next/src/build/edge/createEdgeBundle.ts, packages/open-next/src/build/validateConfig.ts, packages/open-next/src/core/createMainHandler.ts, packages/open-next/src/core/requestHandler.ts, packages/open-next/src/core/resolve.ts, packages/open-next/src/core/routing/util.ts, packages/open-next/src/overrides/converters/aws-cloudfront.ts, packages/open-next/src/overrides/proxyExternalRequest/dummy.ts, packages/open-next/src/overrides/proxyExternalRequest/fetch.ts, packages/open-next/src/overrides/proxyExternalRequest/node.ts, packages/open-next/src/plugins/resolve.ts, packages/open-next/src/types/global.ts, packages/open-next/src/types/open-next.ts, packages/open-next/src/types/overrides.ts
This PR add an option to override the old `proxyRequest` fn that was used for external rewrites.
It also automatically make the proxying when used in the external middleware, no need to do it in a converter or the wrapper.
By default it is the same as before, but it could use `fetch` for the proxying
@vicb PTAL, i haven't tested the fetch part, i'd appreciate some feedback on this
=> Feat: Allow overriding the proxying for external rewrite

.changeset/slow-icons-grin.md, packages/open-next/src/http/openNextResponse.ts
=> fix 304 incorrectly set as 200

.changeset/ten-trainers-boil.md, packages/open-next/src/build/createServerBundle.ts, packages/open-next/src/build/validateConfig.ts, packages/open-next/src/overrides/converters/aws-apigw-v2.ts, packages/open-next/src/overrides/converters/edge.ts, packages/open-next/src/overrides/wrappers/cloudflare-streaming.ts, packages/open-next/src/overrides/wrappers/cloudflare.ts, packages/open-next/src/types/open-next.ts
@conico974 Do you think "cloudflare-streaming" is a reasonable name or "cloudflare-server" would be better (or any other idea)?
The changes are somehow tested - might require minor tweaks later.
I have spread the changes across different commits per unit of work to ease the review.
Thanks!
=> feat: add a cloudflare-streaming wrapper

biome.jsonc
Fix #639
I don't think there is a way to force the changeset bot to follow a specific format. Easiest fix is just to disable biome format for `package.json`
=> Remove package.json from biome format

.changeset/dirty-plums-cheat.md, packages/open-next/src/core/requestHandler.ts, packages/open-next/src/core/routing/middleware.ts, packages/open-next/src/core/routingHandler.ts, packages/open-next/src/overrides/converters/aws-cloudfront.ts, packages/open-next/src/overrides/wrappers/aws-lambda-streaming.ts, packages/open-next/src/overrides/wrappers/cloudflare-streaming.ts, packages/open-next/src/overrides/wrappers/cloudflare.ts, packages/open-next/src/overrides/wrappers/dummy.ts, packages/open-next/src/overrides/wrappers/node.ts, packages/tests-unit/tests/core/routing/middleware.test.ts
Discussed at https://github.com/opennextjs/opennextjs-aws/pull/642#discussion_r1853958888
I'll add the validation in a follow-up PR
=> fix(cloudflare): cloudflare-streaming do not use the edge runtime

.changeset/green-news-give.md, packages/open-next/src/build/createMiddleware.ts, packages/open-next/src/build/edge/createEdgeBundle.ts, packages/open-next/src/build/helper.ts, packages/open-next/src/build/validateConfig.ts, packages/open-next/src/helpers/withCloudflare.ts, packages/open-next/src/overrides/wrappers/cloudflare-edge.ts, packages/open-next/src/overrides/wrappers/cloudflare-node.ts, packages/open-next/src/plugins/resolve.ts, packages/open-next/src/types/open-next.ts
The commit message do not mention "cloudflare-streaming" -> "cloudflare-node" as this was never released officially.
=> refactor(cloudflare): rename the "cloudflare" wrapper to "cloudflare-edge"

packages/open-next/src/overrides/converters/edge.ts
I had missed the edge converter in https://github.com/opennextjs/opennextjs-aws/pull/644
=> fix: type of the edge converter

examples/app-pages-router/package.json, examples/app-router/package.json, examples/pages-router/package.json, examples/shared/package.json, packages/open-next/package.json, packages/open-next/src/http/openNextResponse.ts, packages/utils/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
This PR will add [pnpm catalog](https://pnpm.io/catalogs) for deps that is reused through the repo. Making it easier to maintain. I will open this in draft mode so we can continue working on it. The alternative was using something like [syncpack](https://jamiemason.github.io/syncpack/guide/getting-started/), but that would add another dep so I decided to go with pnpm catalogs instead.
Any suggestions on what more we could add? I have considered using catalog for the other shared deps in `examples/*`, like f.ex `tailwindcss`/`typescript` or `postcss`. Not sure if we want that, and also should we consider using a caret or tilde in any of the catalog versions? 
Btw, I have tested building and deploying the examples apps with this PR, and it works as it should.
=> add: pnpm catalog

packages/open-next/src/build/bundleNextServer.ts, packages/open-next/src/build/createServerBundle.ts, packages/open-next/src/build/edge/createEdgeBundle.ts, packages/open-next/src/build/helper.ts
Default to !BuildOptions#debug
This will be useful for cloudflare as we don't want to minify the code to be able to apply string replace patches (see [this issue](https://github.com/opennextjs/opennextjs-cloudflare/issues/143))
With this change, we can decide not to minify the code whether or not debug is enabled (by overriding the BuildOptions).
Notes:
- `wrangler` will ultimately minify the code anyway
- we plan to migrate the patches to AST transforms to not depend on whether or not the code is minified
=> feat(build): add BuildOptions#minify to enable code minification

biome.jsonc, examples/app-pages-router/app/ssr/page.tsx, examples/app-router/app/ssr/page.tsx
Should we consider turning on this [no-unused-imports](https://biomejs.dev/linter/rules/no-unused-imports/) in `biome.jsonc`?
=> refactor: remove unused imports

.changeset/big-terms-boil.md, .changeset/giant-parrots-hear.md, packages/open-next/src/adapters/image-optimization-adapter.ts, packages/open-next/src/core/requestHandler.ts, packages/open-next/src/core/routing/util.ts, packages/open-next/src/http/openNextResponse.ts, packages/open-next/src/overrides/wrappers/aws-lambda-streaming.ts, packages/open-next/src/overrides/wrappers/aws-lambda.ts, packages/open-next/src/overrides/wrappers/cloudflare-node.ts, packages/open-next/src/overrides/wrappers/node.ts, packages/open-next/src/types/open-next.ts, packages/open-next/src/types/overrides.ts
Returns the response converted from the internal event. 
It fixes a "This ReadableStream did not return bytes" workerd error.
Co-authored-by: conico974 <nicodorseuil@yahoo.fr>
---
This is **part 2 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #664 👈 
- <kbd>&nbsp;1&nbsp;</kbd> #663
=> fix(cloudflare): fix the node wrapper

packages/open-next/src/adapters/plugins/image-optimization/image-optimization.ts
This will make the build work again. We can safely ignore type checking in the entire file, cause its only used for Next <= `14.1`
=> fix: ignore type checking in image-optimization.ts

.changeset/light-shirts-press.md, packages/open-next/src/utils/binary.ts, packages/tests-unit/tests/binary.test.ts
This commit adds `audio/flac` to the `commonBinaryMimeTypes` Set.
Mozilla lists `audio/flac` as a valid media container format in their documentation: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#flac
For my part, I was creating a route handler in my Next.js app (built with SST and opennextjs-aws) that was returning an FLAC file passed through from an S3 bucket. The file is supposed to be played in the client using an Web Audio AudioContext. 
I was mystified why the file size was different than expected when it was returned to the client to be played, and after digging around found that the `isBase64Encoded` response parameter was likely being set to true in `open-next/src/core/routing/utils.ts`.  I've temporarily set my `Content-Type` to …
=> fix: add audio/flac to commonBinaryMimeTypes

.changeset/thirty-grapes-punch.md, packages/open-next/src/core/routing/matcher.ts, packages/tests-unit/tests/core/routing/matcher.test.ts
Related https://github.com/opennextjs/opennextjs-aws/issues/670
I was trying to figure out how to add (and run) a unit test in `matcher.test.ts` but then I saw [this issue](https://github.com/opennextjs/opennextjs-aws/issues/539) that mentions all unit tests are broken (?).
If e2e test(s) are required I'd appreciate any help as I'm not very familiar. And let me know if you need something else.
Thanks!
=> fix(aws): add missing base path to data routes

.changeset/three-cobras-mix.md, packages/open-next/src/overrides/proxyExternalRequest/node.ts
There was an user in our Discord that complained about his lambda were outputting tons of logging, but he didn't have `OPEN_NEXT_DEBUG` set to any truthy value. Turns out that the `node.ts` module from the `proxyExternalRequest` override imported debug, and error from `node:console` instead of our own in `adapters/logger`.
=> fix: import correct logger

packages/open-next/src/build/edge/createEdgeBundle.ts
this is needed to resolve https://github.com/opennextjs/opennextjs-cloudflare/issues/177
=> fix: make sure that the `__import_unsupported` patch is applied in Cloudflare as well

.changeset/spotty-chairs-pretend.md, packages/open-next/src/adapters/config/index.ts, packages/open-next/src/adapters/config/util.ts, packages/open-next/src/adapters/middleware.ts, packages/open-next/src/core/requestHandler.ts, packages/open-next/src/core/routing/routeMatcher.ts, packages/open-next/src/core/routingHandler.ts, packages/open-next/src/plugins/edge.ts, packages/open-next/src/types/open-next.ts, packages/tests-unit/tests/core/routing/routeMatcher.test.ts
This PR will help #665.
This may also allow us in the future to use https://github.com/vercel/next.js/blob/4d1613d049037b2b39295a9479c9f8c9a12df907/packages/next/src/server/base-server.ts#L1581 instead of `getRequestHandler`
=> add additional metadata to RoutingResult

packages/open-next/src/build/edge/createEdgeBundle.ts
I find this version easier to read, but feel free to close...
=> refactor: code cleanup

packages/open-next/src/overrides/wrappers/cloudflare-node.ts
Fixes:
```
✘ [ERROR] TypeError: Response with null body status (101, 204, 205, or 304) cannot have a body.
```
For cached responses
=> fix(cloudflare): No body for 101, 204, 205, or 304 status codes

.changeset/many-cooks-breathe.md, packages/open-next/src/build/createAssets.ts
That should help with https://github.com/opennextjs/opennextjs-cloudflare/pull/194
=> fix: fetch cache does not depend on tag cache being enabled

.changeset/moody-coins-build.md, packages/open-next/src/core/routing/util.ts, packages/tests-unit/tests/core/routing/util.test.ts
=> fix html cache headers with i18n

packages/open-next/src/adapters/util.ts
This is a quick change to avoid warnings such as:
when using the Cloudflare adapter
I am not a huge fan of this change but, for a quick fix which doesn't require too much refactoring in the aws package, I think it's either this or patching the aws code on the Cloudflare adapter (as I've done in https://github.com/opennextjs/opennextjs-cloudflare/pull/211).
(A more proper fix would be to make the aws code configurable so that when used by the Cloudflare adapter the `setNodeEnv` is either never called, thus three shaken away, or becomes a no-op function, but that as I referred to before would be a much bigger change, which might not be worth it right now)
=> change `setNodeEnv` code to avoid warnings when using the Cloudflare adapter

.changeset/many-elephants-sing.md, packages/open-next/src/core/routing/middleware.ts, packages/open-next/src/overrides/wrappers/cloudflare-edge.ts
fixes https://github.com/opennextjs/opennextjs-aws/issues/687
=> city-encoding

.changeset/forty-cars-smile.md, packages/open-next/package.json, packages/open-next/src/build/validateConfig.ts, packages/open-next/src/overrides/imageLoader/fs-dev.ts, packages/open-next/src/overrides/incrementalCache/fs-dev.ts, packages/open-next/src/overrides/queue/direct.ts, packages/open-next/src/overrides/tagCache/fs-dev.ts, packages/open-next/src/overrides/wrappers/dummy.ts, packages/open-next/src/overrides/wrappers/express-dev.ts, packages/open-next/src/types/open-next.ts, pnpm-lock.yaml
This PR adds a bunch of overrides that is useful to run OpenNext locally.
They can be used in the config file: 
```ts
import type {OpenNextConfig} from "@opennextjs/aws/types/open-next.js"
export default {
default: {
override: {
wrapper: "express-dev",
converter: "node",
incrementalCache: "fs-dev",
queue: "direct",
tagCache: "fs-dev"
}
},
imageOptimization: {
override: {
wrapper: "dummy",
converter: "dummy"
},
loader: "fs-dev",
// This part is not needed on arm linux, and image optimization will only work in linux
install: {
arch: "x64",
packages: ["sharp"]
}
},
} satisfies OpenNextConfig
```
`"direct"` queue could also be used to remove the need to have a queue. It should not be used where `waitUntil` is not properly supported as it means that ISR will wait for the revalidation to be …
=> Feat: Add dev overrides

examples/app-router/app/api/og/route.tsx, examples/app-router/app/og/opengraph-image.tsx, examples/app-router/app/og/page.tsx, packages/tests-e2e/tests/appRouter/og.test.ts
This PR will add e2e testing for `next/og` and `opengraph-image.tsx` in the app router
- An empty page on the route `/og` that should have an opengraph image present in the metatags.
- An API route on `/api/og` that returns an `ImageResponse` from `next/og`.
=> e2e: add open-graph image tests

.changeset/thirty-donuts-buy.md, packages/open-next/src/plugins/edge.ts, packages/open-next/src/plugins/replacement.ts
Some of the filters were missing Windows separators.
=> fix: esbuild plugins not matching windows paths

.changeset/little-geese-study.md, packages/open-next/src/build/createServerBundle.ts
ref: https://github.com/opennextjs/opennextjs-cloudflare/pull/234#discussion_r1907320812
=> fix: host not in route handler url when using external middleware

.changeset/hungry-geckos-knock.md, packages/open-next/src/build/createImageOptimizationBundle.ts, packages/open-next/src/build/createServerBundle.ts, packages/open-next/src/build/edge/createEdgeBundle.ts, packages/open-next/src/plugins/edge.ts, packages/open-next/src/plugins/resolve.ts, packages/open-next/src/utils/regex.ts, packages/tests-unit/tests/utils/regex.test.ts
- Create a new utility for constructing regular expressions with cross-platform paths.
- Update usage to use the new utility.
=> refactor: use utility for cross-platform path regex construction

.changeset/thin-feet-love.md, packages/open-next/package.json, packages/open-next/src/adapters/cache.ts, packages/open-next/src/core/createMainHandler.ts, packages/open-next/src/core/requestHandler.ts, packages/open-next/src/core/resolve.ts, packages/open-next/src/core/routing/util.ts, packages/open-next/src/overrides/cdnInvalidation/cloudfront.ts, packages/open-next/src/overrides/cdnInvalidation/dummy.ts, packages/open-next/src/plugins/resolve.ts, packages/open-next/src/types/global.ts, packages/open-next/src/types/open-next.ts, packages/open-next/src/types/overrides.ts, packages/tests-unit/tests/adapters/cache.test.ts, packages/tests-unit/tests/core/routing/util.test.ts, pnpm-lock.yaml
Fix #658 
~~Still a bit of work to do on this one, it will require a refactor of `InternalEvent` (or `RoutingResult`) and the routingHandler so that we have access to the information we need (Or maybe we can use the async hook context)~~
Should be ready for review
=> Feat Automatic cdn invalidation

.changeset/sweet-kiwis-agree.md, packages/open-next/src/adapters/cache.ts, packages/open-next/src/overrides/tagCache/dynamodb-lite.ts, packages/open-next/src/overrides/tagCache/dynamodb.ts, packages/open-next/src/types/global.ts, packages/tests-unit/tests/adapters/cache.test.ts
@conico974 Actually, this might be a breaking change...
So maybe I should deprecate instead and add a changeset then we can remove later.
WDYT?
=> refactor(cache): deprecate global disableDynamoDBCache and disableIncrementalCache

.changeset/smart-carrots-build.md, packages/open-next/src/core/edgeFunctionHandler.ts, packages/open-next/src/types/global.ts
the values in `self._ENTRIES` can be promises so they need to be awaited before using them, AFAICT that's also what Next.js  does: [source code](
https://github.com/vercel/next.js/blob/6d17cc6b0f3c153d2405ac97e862da2e9008258f/packages/next/src/server/web/sandbox/sandbox.ts#L119)
this PR makes sure that such values are properly awaited
=> make sure edge function entries are properly awaited

examples/app-pages-router/middleware.ts, packages/tests-e2e/tests/appPagesRouter/api.test.ts
This PR add test for #704
I've added a `@ts-expect-error` for the top level await, i didn't want to go down the rabbit hole of finding the issue here (middleware is somehow considered a cjs file and if set as a module, `next/server` import does not work anymore)
There is also a build time warning, but it still works both with `next start` or in the e2e test
=> add e2e test for top-level await in middleware

.changeset/orange-impalas-repeat.md, packages/open-next/src/adapters/logger.ts
People were reporting getting this error in SST Console: 
```Name: 'S3Client', commandName: 'GetObjectCommand', input: { Bucket: 'myapp-dev-myappassets-bvaaaaa', Key: '_cache/kbhQ5yYbaaaaaaaAa/dk.cache' }, error: NoSuchKey: The specified key does not exist.```
The error gets downplayed correctly but turns out we are not returning when an error is downplayed so this [line](https://github.com/opennextjs/opennextjs-aws/blob/9e770b53701e96f2007926b86450699696763bae/packages/open-next/src/adapters/logger.ts#L72) gets run aswell. This PR fixes this.
=> fix: return when an error is downplayed

packages/open-next/src/build/createAssets.ts, packages/open-next/src/build/createServerBundle.ts, packages/open-next/src/build/helper.ts
Will also be needed for `@opennextjs/cloudflare`
=> refactor: introduce a getPackagePath helper

packages/open-next/src/build/createAssets.ts, packages/open-next/src/build/generateOutput.ts, packages/open-next/src/build/helper.ts
a bit simpler interface (as I'm introducing it in cf)
=> refactor: getBuildId takes the BuildOptions

.changeset/smooth-crabs-end.md, packages/open-next/src/build/helper.ts
fixes #714
Tested in opennext-cloudflare, works nicely
=> Dump ESBuild build metadata to `<bundle>.meta.json` in debug mode

.changeset/new-beers-worry.md, packages/open-next/src/overrides/proxyExternalRequest/fetch.ts, packages/tests-unit/tests/overrides/proxyExternalRequest/fetch.test.ts
this change removes `cf-connecting-header` headers from requests being sent to external urls during rewrites, this allows such overrides, when run inside a Cloudflare worker to rewrite to urls also hosted on Cloudflare
_____
With this change the [`Rewrite to external image` test](
https://github.com/opennextjs/opennextjs-aws/blob/main/packages/tests-e2e/tests/pagesRouter/rewrite.test.ts#L20-L25) passes when run in the Cloudflare repo
_____
Original conversation: https://github.com/opennextjs/opennextjs-aws/pull/723#pullrequestreview-2590722699
=> fix: remove `cf-connecting-ip` headers from external override requests

packages/open-next/src/adapters/cache.ts, packages/open-next/src/core/routing/cacheInterceptor.ts, packages/open-next/src/overrides/incrementalCache/multi-tier-ddb-s3.ts, packages/open-next/src/types/overrides.ts
Very minor but I think it would be nice if we could return `null` as the incremental cache `get` result instead of being forced to return an empty object:
https://github.com/opennextjs/opennextjs-cloudflare/blob/642c3d2e654ef830b7957faecb1cbe26bae469ed/packages/cloudflare/src/api/kvCache.ts#L46
=> allow `null` to be returned as an incremental cache get result

packages/open-next/src/plugins/resolve.ts
ESBuild recommends callbacks [to be async](https://esbuild.github.io/plugins/#on-load) because many can run in parallel
=> refactor: make onLoad async

packages/open-next/src/core/routing/cacheInterceptor.ts, packages/open-next/src/core/routing/queue.ts, packages/open-next/src/core/routing/util.ts
Had to move this utility to its own file so that I could import it into a queue without getting build errors due to the original file trying to import from the configs stuff.
=> move generate message id util to own file

.changeset/pink-papayas-smoke.md, packages/open-next/src/adapters/edge-adapter.ts, packages/open-next/src/adapters/image-optimization-adapter.ts, packages/open-next/src/adapters/middleware.ts, packages/open-next/src/core/requestHandler.ts, packages/open-next/src/overrides/wrappers/aws-lambda-streaming.ts, packages/open-next/src/overrides/wrappers/aws-lambda.ts, packages/open-next/src/overrides/wrappers/cloudflare-edge.ts, packages/open-next/src/overrides/wrappers/cloudflare-node.ts, packages/open-next/src/overrides/wrappers/dummy.ts, packages/open-next/src/overrides/wrappers/express-dev.ts, packages/open-next/src/overrides/wrappers/node.ts, packages/open-next/src/types/global.ts, packages/open-next/src/types/open-next.ts, packages/open-next/src/types/overrides.ts, packages/open-next/src/utils/promise.ts
@conico974 this a POC to fix https://github.com/opennextjs/opennextjs-aws/issues/713
I tested locally that
- `waitUntil` is available for middleware and the server
- `waitUntil` is fixed when there is a nested request inside a long running request
The handler API is changed so this is a breaking change.
What do you think?
=> refactor: `waitUntil` passed around via ALS

packages/open-next/src/types/global.ts
Minor edits.
I don't think "Only available in main functions or in the external middleware with `enableCacheInterception` set to `true`." were accurate?
=> update docs for global

packages/open-next/package.json, pnpm-lock.yaml
Two deps were not used in our `open-next` package:
- `@esbuild-plugins/node-resolve`
- `promise.series`
=> fix: remove unused deps

.changeset/stale-walls-sin.md, packages/open-next/src/build/compileTagCacheProvider.ts, packages/open-next/src/types/open-next.ts
Turns out we didn't have the correct typing for `tagCache` in `initializationFunction`. We also didn't provide the override to `compileTagCacheProvider`.
=> fix: add correct typing to tagCache in initializationFunction

packages/open-next/package.json
Updates the `package.json` `exports` field to split into `default` and `types` to fix issue with TypeScript being unable to reference types such as:
```ts
import type { OpenNextConfig } from "open-next/types/open-next";
```
Error message: `Cannot find module 'open-next/types/open-next' or its corresponding type declarations. ts(2307)`
=> Update package.json exports for types imports

packages/open-next/package.json, packages/open-next/src/build/createAssets.ts, packages/open-next/src/types/cache.ts, packages/open-next/src/types/open-next.ts
I want to re-use the value instead of importing the generated file.
I also had to add back the `typesVersions` that was removed in https://github.com/opennextjs/opennextjs-aws/pull/747 as it broke builds and imports for the cloudflare adapter.
=> return meta files from createAssets()

.changeset/lucky-horses-worry.md, packages/open-next/src/build/createImageOptimizationBundle.ts, packages/open-next/src/overrides/imageLoader/s3-lite.ts, packages/open-next/src/types/open-next.ts
- Uses `aws4fetch`
- New env variable `BUCKET_REGION`. Falls back to `AWS_REGION` ?? `AWS_DEFAULT_REGION` if undefined. This way no change in IAC is needed for most users. 
Add an `open-next.config.ts` with these options: 
```ts
import type { OpenNextConfig } from '@opennextjs/aws/types/open-next';
const config = {
default: {},
imageOptimization: {
loader: 's3-lite',
},
} satisfies OpenNextConfig;
export default config;
```
=> add: s3-lite override for imageLoader

.changeset/smooth-laws-pull.md, packages/open-next/src/adapters/edge-adapter.ts, packages/open-next/src/adapters/middleware.ts, packages/open-next/src/core/requestHandler.ts, packages/open-next/src/core/routing/matcher.ts, packages/open-next/src/core/routing/middleware.ts, packages/open-next/src/core/routing/util.ts, packages/open-next/src/core/routingHandler.ts, packages/open-next/src/overrides/converters/aws-apigw-v1.ts, packages/open-next/src/overrides/converters/aws-apigw-v2.ts, packages/open-next/src/overrides/converters/aws-cloudfront.ts, packages/open-next/src/overrides/converters/edge.ts, packages/open-next/src/overrides/converters/node.ts, packages/open-next/src/overrides/converters/utils.ts, packages/open-next/src/overrides/wrappers/cloudflare-node.ts, packages/open-next/src/types/open-next.ts, packages/tests-unit/tests/converters/aws-apigw-v1.test.ts, packages/tests-unit/tests/converters/aws-apigw-v2.test.ts, packages/tests-unit/tests/converters/aws-cloudfront.test.ts, packages/tests-unit/tests/converters/node.test.ts, packages/tests-unit/tests/core/routing/matcher.test.ts, packages/tests-unit/tests/core/routing/middleware.test.ts
fixes https://github.com/opennextjs/opennextjs-aws/issues/719
edit: One thing I need to check is the base path, we should probably add it when constructing URLs (i.e. 404, 500)
@conico974 could you please review and maybe run the aws integration tests when this looks ok?
cf tests are green with this PR.
Thanks!
=> refactor: internalEvent.url is a full URL

.changeset/nasty-geckos-sniff.md, packages/open-next/src/adapters/config/index.ts, packages/open-next/src/adapters/config/util.ts, packages/open-next/src/build/compileConfig.ts, packages/open-next/src/build/constant.ts, packages/open-next/src/build/copyTracedFiles.ts, packages/open-next/src/build/createMiddleware.ts, packages/open-next/src/build/createServerBundle.ts, packages/open-next/src/build/edge/createEdgeBundle.ts, packages/open-next/src/build/middleware/buildNodeMiddleware.ts, packages/open-next/src/core/edgeFunctionHandler.ts, packages/open-next/src/core/nodeMiddlewareHandler.ts, packages/open-next/src/core/routing/middleware.ts, packages/open-next/src/core/routing/util.ts, packages/open-next/src/core/util.ts, packages/open-next/src/plugins/edge.ts, packages/open-next/src/plugins/externalMiddleware.ts, packages/open-next/src/types/next-types.ts, packages/open-next/src/types/open-next.ts, packages/open-next/src/utils/promise.ts, packages/tests-unit/tests/core/routing/middleware.test.ts
This should be close to being ready
Couple of issues that needed to be resolved:
=> feat: node middleware

.changeset/fair-pots-give.md, packages/open-next/src/core/routing/i18n/index.ts, packages/tests-unit/tests/core/routing/i18n.test.ts
With `localeDetection:false` we should still detect the locale for domain based thing.
=> fix localeDetection false

examples/pages-router/src/pages/api/dynamic/[slug].ts, examples/pages-router/src/pages/api/dynamic/catch-all-optional/[[...slug]].ts, examples/pages-router/src/pages/api/dynamic/catch-all/[...slug].ts, examples/pages-router/src/pages/api/dynamic/precedence/route.ts, examples/pages-router/src/pages/api/hello.ts, packages/tests-e2e/tests/pagesRouter/api.test.ts
For #763, add e2e for API routes in `pagesRouter` example app:
- Hello world in `/api/hello.ts` 
- Dynamic API route in `/api/dynamic/[slug].ts` 
- Catch all route in `/api/dynamic/catch-all/[...slug].ts` 
- Catch all optional route in `/api/dynamic/catch-all-optional/[[...slug]].ts` 
I also wanted to have a last predefined route which would take precedence over those above as stated in Next docs [caveats](https://nextjs.org/docs/pages/building-your-application/routing/api-routes#caveats). Turns out its not taking precedence as stated in the docs. Same behavior in `next start`. I will open an issue in Next for this. For now I just added `.skip()` in the e2e.
=> add: e2e for api routes in pages router

.changeset/red-starfishes-wave.md, examples/pages-router/next.config.ts, examples/pages-router/src/pages/api/query.ts, packages/open-next/src/core/routing/matcher.ts, packages/tests-e2e/tests/pagesRouter/rewrite.test.ts, packages/tests-unit/tests/core/routing/matcher.test.ts
This PR fix #766
They were 2 different issues described there: 
- Query params defined in the destination of a rewrite were not forwarded as expected
-  Internal destination that are api route should be stripped from the appended locale. (If `locale` is not set to false, next will always transform in rewrite with an appended locale, but it expects the api route to be not locale prefixed)
@nicholas-c Could you confirm that it fixes your issue
=> Fix rewrite query not forwarded and api destination

.changeset/tall-pets-hammer.md, packages/open-next/src/build/copyTracedFiles.ts
In Next `15.2.2` (and maybe earlier minor and patch) sharp seems have some deps under the scope `@img/*`. (i.e [@img/sharp-linux-x64](https://www.npmjs.com/package/@img/sharp-linux-x64)) 
The issue was discovered in this [comment](https://github.com/sst/sst/issues/5534#issuecomment-2713713849). 
Without this fix the default server function might end up being 32mb+ larger than it has to.
=> fix: ignore @img in copyTracedFiles

packages/tests-e2e/tests/appRouter/revalidateTag.test.ts
I was seeing some flakiness when running the e2es locally in Cloudflare purely due to the fact that the test ran in less than 1 second and so the seconds in the date did not change.
=> add timeout in revalidatePath test as locally can run too fast

.changeset/sour-boxes-jump.md, packages/open-next/src/adapters/logger.ts, packages/open-next/src/core/routing/cacheInterceptor.ts, packages/open-next/src/core/routing/util.ts, packages/open-next/src/types/overrides.ts, packages/tests-unit/tests/core/routing/util.test.ts
Add additional params to the queue
Also add a `.js` to the import in `logger` to fix an issue with test in cloudflare
=> Feat Add additional params to the queue override

.changeset/smart-grapes-shake.md, packages/open-next/src/overrides/wrappers/express-dev.ts
we didn't `set-cookie` in `express-dev` wrapper. should we call: 
```ts
res.flushHeaders();
res.uncork();
```
aswell? like in the `node` wrapper?
=> fix: add cookies in express-dev wrapper

.changeset/metal-news-watch.md, packages/open-next/src/core/routing/middleware.ts
For #772
Internally Next uses `x-middleware-set-cookie` and `x-middleware-next`. These are then removed on the response by Next code, but since we have a custom middleware we need to remove it our self.
=> fix: remove internal next headers in middleware response

packages/tests-e2e/tests/appRouter/methods.test.ts
For some reason my own deployed `app-router` had a comma in the `cache-control` value, but the `app-router` that is deployed from here does not.
=> fix e2e methods static get route

packages/open-next/package.json, packages/open-next/src/adapters/config/util.ts, packages/open-next/src/build/copyTracedFiles.ts, packages/open-next/src/build/createMiddleware.ts, packages/open-next/src/build/createServerBundle.ts, packages/open-next/src/build/edge/createEdgeBundle.ts, packages/open-next/src/build/patch/astCodePatcher.ts, packages/open-next/src/build/patch/codePatcher.ts, packages/open-next/src/logger.ts, packages/open-next/src/plugins/content-updater.ts, packages/tests-unit/tests/build/patch/codePatcher.test.ts, pnpm-lock.yaml
This PR replaces #741.
This PR allow to apply patch to traced files at build time, as well as provide a way to pass esbuild plugins when needed.
2 PR will depend on this one : #783 and #782
=> Feat: Generic Code Patching

.changeset/khaki-rice-applaud.md, examples/app-router/app/isr-data-cache/page.tsx, examples/app-router/next.config.ts, packages/open-next/src/build/createServerBundle.ts, packages/open-next/src/build/patch/patchFetchCacheISR.ts, packages/open-next/src/core/requestHandler.ts, packages/tests-e2e/tests/appRouter/isr.test.ts, packages/tests-unit/tests/build/patch/patchFetchCacheISR.test.ts
Patch the fetch cache and `unstable_cache` so that they does not get revalidated (if not necessary) by our ISR revalidation request.
It replaces `patchAsyncStorage`.
Can be removed once this gets merged : https://github.com/vercel/next.js/pull/72082
This PR depends on #781. Should not be merged before it
=> Fix fetch cache for isr

packages/open-next/src/build/patch/astCodePatcher.ts
Needed to re-use the functions in the cloudflare adapter
=> re-export ast-grep types

.changeset/heavy-moles-share.md, packages/open-next/src/core/requestHandler.ts
Closes #789
Turns out we were not passing the correct headers to the response when streaming is used.
=> fix: external rewrite for streaming

.changeset/gorgeous-rocks-appear.md, packages/open-next/src/build.ts, packages/open-next/src/build/compileConfig.ts
The cloudflare adapter will move away from using an internal middleware.
With this change we can still force the compilation of an edge configuration when the middleware is part of the server bundle.
(Longer term we might want to find a better solution to detect this)
=> Add a `compileEdge` parameter to `compileOpenNextConfig`

packages/open-next/src/build/createServerBundle.ts
This caused an issue in Cloudflare, see https://github.com/opennextjs/opennextjs-cloudflare/pull/509
=> refactor: re-export the handler by name

.changeset/perfect-cobras-move.md, packages/open-next/src/build/createServerBundle.ts, packages/open-next/src/build/edge/createEdgeBundle.ts, packages/open-next/src/plugins/edge.ts
Related to https://github.com/opennextjs/opennextjs-cloudflare/issues/471
2 fixes in this PR:
- For bundled middleware, we do copy the source file (in `createServerBundle` but we also need to copy .wasm files
- The second fix is specific for the edge, the file name is used in Next middleware source, then if we re-use the same name to import the same file, ESBulid will append a 2 and Next can not reference this import.
=> fix(middleware): Support wasm in bundled middleware

.changeset/fair-ducks-shake.md, packages/open-next/src/overrides/wrappers/node.ts
Since this PR: https://github.com/nodejs/node/pull/50167 merged in node 21, calling `.uncork()` without having called `.cork()`before seems to block future write to the stream.
=> fix stream not returning data in node 21+ with node wrapper

examples/app-router/middleware.ts, packages/open-next/src/core/routing/middleware.ts
When doing `pnpm build && pnpm start` in `app-router`. You will get an error when trying to run the e2e test locally for `/methods/post/formdata`:
`⨯ TypeError: Content-Type was not one of "multipart/form-data" or "application/x-www-form-urlencoded".`
The reason is this line: https://github.com/opennextjs/opennextjs-aws/blob/fbe09aed4280a5c0820efda74230a12c7cd5bf2c/examples/app-router/middleware.ts#L31
I guess we need to pass in the request headers already coming in. Reason it works once deployed is because OpenNext doesn't remove them like `next start`.
I also removed an unused variable in `/src/core/routing/middleware.ts`
=> fix: merge request headers in middleware in app-router example

examples/app-router/app/isr/dynamic-params-false/[id]/page.tsx, examples/app-router/app/isr/dynamic-params-true/[id]/page.tsx, packages/tests-e2e/tests/appRouter/isr.test.ts
E2E for `dynamicParams`  in `app-router`:
- dynamicParams set as `true` in `/isr/dynamic-params-true/[id]`
- dynamicParams set as `false` in `/isr/dynamic-params-false/[id]`
=> add e2e for dynamicparams in app-router

.changeset/grumpy-pens-shake.md, packages/open-next/src/core/routing/util.ts, packages/tests-unit/tests/core/routing/util.test.ts
Fully static pages router page (without `getStaticProps`) can get an incorrect cache-control headers if the `x-middleware-prefetch` header is present
=> fix for fully-static pages router page

.changeset/mean-icons-tap.md, examples/app-pages-router/middleware.ts, packages/open-next/src/core/routing/middleware.ts, packages/tests-e2e/tests/appPagesRouter/middleware.test.ts, packages/tests-unit/tests/core/routing/middleware.test.ts
Fix 2 small issues with the middleware.
- Directly returning a fetch from the middleware crashed because of immutable headers
- Returning a `Response` with an empty body which was not a redirect was not working
=> Fix middleware fetch

packages/open-next/src/build/createServerBundle.ts, packages/open-next/src/build/patch/patches/index.ts
sorry @conico974 I missed that during the review
=> refactor: export patchBackgroundRevalidation from patches/index.js

.changeset/lemon-needles-fold.md, packages/open-next/src/adapters/cache.ts, packages/tests-unit/tests/adapters/cache.test.ts
See https://github.com/opennextjs/opennextjs-cloudflare/issues/576
Called from `node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js`
```js
_workStore_incrementalCache.revalidateTag(workStore.revalidatedTags||[])
```
=> fix(tagCache): do not call writeTags with an empty list

.changeset/unlucky-shrimps-lick.md, packages/open-next/src/adapters/image-optimization-adapter.ts, packages/tests-e2e/tests/appRouter/image-optimization.test.ts
For #826 
In versions 13, 14, and 15, `next start` returns a 400 Bad Request if `validateImageParams` returns an `errorMessage`. We should align with this behavior.
=> fix: should return 400 in image optimization when Next passes errorMessage

.changeset/smooth-tomatoes-compete.md, packages/open-next/src/build/copyTracedFiles.ts
In the cloudflare adapter, we want to copy files used via the "workerd" build conditions.
To be able to do this this PR updates `copyTracedFiles` to return a map of traced node packages.
It maps the original path of the package to the path in `.open-next`.
As a follow up, we might integrate that better with the patch system.
Today, `applyCodePatches` assumes that a patch will update file content.
We could modify `applyCodePatches` to take a list of `Patch`. 
The `Patch` class would be instantiated with `options, tracedFiles, manifests, nodePackages, nextVersion` and have a public `apply` method.
We could then have derived `PatchFileContent`, `PatchCopyFile`, ... classes.
=> trace node packages

.changeset/six-icons-knock.md, packages/open-next/src/plugins/edge.ts, packages/open-next/src/utils/normalize-path.ts
- Normalizes the path that gets used for the middleware in the edge plugins.
=> fix edge middleware path on windows

.changeset/lucky-ghosts-knock.md, packages/open-next/src/adapters/cache.ts, packages/open-next/src/types/cache.ts, packages/open-next/src/types/overrides.ts
This PR will compute the correct revalidate value at runtime for ISR/SSG route to be used by the incremental cache
It depends on #832, just to avoid deleting and recreating a cloudfront distribution every time i switch branch.
I'll rebased #820 on this as well
=> Pass `revalidate` value to the incremental cache for ISR/SSG route

.changeset/khaki-dragons-build.md, examples/app-pages-router/app/rewrite-destination/page.tsx, examples/app-pages-router/middleware.ts, packages/open-next/src/core/routing/middleware.ts, packages/tests-e2e/tests/appPagesRouter/middleware.rewrite.test.ts
This PR fixes search params with multiple values set in the middleware for rewrite
fixes https://github.com/opennextjs/opennextjs-cloudflare/issues/537
=> Fix middleware search params

examples/pages-router/src/pages/amp/index.tsx, examples/pages-router/src/pages/head/index.tsx, packages/tests-e2e/tests/pagesRouter/amp.test.ts, packages/tests-e2e/tests/pagesRouter/head.test.ts
=> add e2e for next/head and next/amp in pages router

.changeset/breezy-adults-behave.md, examples/app-router/app/cookies/page.tsx, examples/app-router/middleware.ts, packages/open-next/src/core/requestHandler.ts, packages/open-next/src/core/routing/middleware.ts, packages/tests-e2e/tests/appRouter/middleware.cookies.test.ts
For #850
We should remove `x-middleware-set-cookie` from `filteredHeaders`. Instead we remove it on the `overwrittenResponseHeaders` which will be passed to the response. 
`reqProps` in `requestHandler.ts` will use the original `headers` object, and pass it into `processRequest`. This makes sure we will see the header on initial render when using `cookies().get()` from Next.
=> fix: Ensure cookies set in middleware are available on initial render

.changeset/eleven-books-yawn.md, packages/open-next/src/core/routing/cacheInterceptor.ts
This fix the index page not catched by the cache interceptor
=> Fix index page with cache interceptor

.changeset/large-forks-decide.md, examples/pages-router/src/pages/fallback-intercepted/[...slugs].tsx, examples/pages-router/src/pages/fallback-intercepted/[slug].tsx, examples/pages-router/src/pages/fallback-intercepted/ssg.tsx, examples/pages-router/src/pages/fallback-intercepted/static.tsx, examples/pages-router/src/pages/fallback/[slug].tsx, packages/open-next/src/core/requestHandler.ts, packages/open-next/src/core/routing/matcher.ts, packages/open-next/src/core/routing/routeMatcher.ts, packages/tests-e2e/tests/pagesRouter/fallback.test.ts, packages/tests-unit/tests/core/routing/matcher.test.ts
Dynamic route with fallback false can wrongly intercept and return 404 for routes that intersect with them.
Fix #677 and https://github.com/opennextjs/opennextjs-cloudflare/issues/611
=> Fix fallback false

.changeset/bright-pants-drum.md, packages/open-next/src/build/compileConfig.ts
Set `process.env.NODE_ENV` to production during edge config compilation to avoid defaulting to development.
=> Fix NODE_ENV in edge config compilation

.changeset/cuddly-dingos-walk.md, packages/open-next/src/core/routing/matcher.ts, packages/open-next/src/utils/normalize-path.ts, packages/tests-unit/tests/core/routing/matcher.test.ts
Let's say you had the following middleware function:
```ts
export async function middleware(request: NextRequest) {
return NextResponse.redirect(new URL("/foo", request.url))
}
```
A request to `https://yourdomain.com//evil.com` would result in `request.url ===  "https://evil.com"`, leading to a malicious redirect. Here we redirect these bad requests containing repeated slashes to a sanitised path.
=> Redirect requests with repeated slashes

.changeset/popular-candles-watch.md, packages/open-next/src/build/createMiddleware.ts
prisma's wasm was not being copied into the middleware directory, which was throwing errors when prisma was being used in the middleware with the authjs database adaptor.
added the copyMiddlewareResources which is already being used in createServerBundle
=> fix(middleware): copy wasm files for middleware

.changeset/polite-teachers-doubt.md, packages/open-next/package.json, packages/open-next/src/plugins/edge.ts, pnpm-lock.yaml, pnpm-workspace.yaml
For #846
I ran into 2 problems after bumping `esbuild`. The first one was a warning during building with OpenNext: 
The second problem was that `onResolve` filter error as indicated in the original issue.
To solve them I reordered the `exports` in `package.json`, and I also removed the `/g` at the end from the RegEx filter. This seemed to solve those issues.
I then built and deployed all Next versions from 12-15. I also ran the E2E for Next 14-15. It seems to work fine.
=> chore: bump esbuild to latest version

.changeset/new-wombats-crash.md, packages/open-next/src/build/createServerBundle.ts, packages/open-next/src/build/patch/patches/dropBabel.ts, packages/open-next/src/build/patch/patches/index.ts, packages/tests-unit/tests/build/patch/patches/dropBabel.test.ts
Supersedes https://github.com/opennextjs/opennextjs-cloudflare/pull/702
Drop the babel dep to save ~4MB on the bundle size.
Details:
- Empty `NextServer#runMiddleware`
- Empty `NextServer#runEdgeFunction`
- Drop `node-environment-extensions/error-inspect`
Tested with the cloudflare adapter
=> perf: drop `babel` to reduce the server bundle size

packages/open-next/package.json, packages/tests-unit/package.json, packages/tests-unit/tests/build/patch/patches/patchFetchCacheWaitUntil.test.ts, packages/tests-unit/tests/build/patch/patches/patchNextServer.test.ts, packages/tests-unit/tests/build/patch/patches/util.ts, pnpm-lock.yaml
IMO it makes the tests much more readable
=> refactor: Use diff in patch tests rather than raw output

.changeset/stale-years-arrive.md, packages/open-next/src/build/copyTracedFiles.ts, packages/open-next/src/types/next-types.ts
The inlining of Critical CSS with the optimizeCss feature doesn't work when using Next.js 15.3.3 (Page Router) and @opennextjs/aws 3.6.5.
The optimizeCss feature relies on the CSS files being present in the server-function bundle. During page rendering (e.g., during ISR or revalidation), a server function using the Critters library attempts to locate the CSS files used on the page and inline them in the HTML. Without these files in the server-function bundle, the inlining process fails.
These changes make the bundling process include `.next/static/css` files in the server-function bundle.
Detailed information is in the attached issue below.
https://github.com/opennextjs/opennextjs-aws/issues/903
=> feat: add css files to server bundle for optimizeCss feature to work

.changeset/happy-pandas-hope.md, packages/open-next/src/core/routing/matcher.ts, packages/tests-unit/tests/core/routing/matcher.test.ts
fix for the missing basePath for dataRoutes (#897)
=> fix dataRoutes omitting basePath

packages/open-next/src/types/next-types.ts
The deployment id is needed for skew protection
=> add NextConfig#deploymentId

.changeset/orange-badgers-cross.md, examples/sst/stacks/AppRouter.ts, packages/open-next/src/adapters/edge-adapter.ts, packages/open-next/src/adapters/middleware.ts, packages/open-next/src/core/requestHandler.ts, packages/open-next/src/core/routing/util.ts, packages/open-next/src/core/routingHandler.ts, packages/open-next/src/utils/promise.ts, packages/tests-e2e/tests/appRouter/headers.test.ts, packages/tests-e2e/tests/pagesRouter/header.test.ts
Introduce an environment variable `OPEN_NEXT_REQUEST_ID_HEADER` to append the request ID to headers.
The requestId is also now shared between the middleware and the server in case of an external middleware
Close #913
=> Add request ID handling

packages/tests-e2e/tests/appRouter/og.test.ts
Fixes https://github.com/opennextjs/opennextjs-aws/actions/runs/16282041804/job/45973465372#step:17:239
=> fix(e2e): update md5sum for og image

.changeset/tricky-pans-cross.md, examples/app-router/open-next.config.local.ts, examples/app-router/package.json, examples/app-router/tsconfig.json, examples/pages-router/open-next.config.local.ts, examples/pages-router/package.json, packages/open-next/src/build/createServerBundle.ts, packages/open-next/src/core/requestHandler.ts, pnpm-lock.yaml, pnpm-workspace.yaml
Migrate to a canary version for now (we need to wait for 15.4.2)
Enable local execution of some examples (first step to run e2e test without deploying)
And fix the page router functionality. This one needs additional testing and be restricted to versions above 15.4.2.
All e2e works on this PR.
It should also close #848 (again needs additional testing)
=> Fix for Next 15.4+

.changeset/forty-paws-nail.md, packages/open-next/src/build/patch/codePatcher.ts, packages/open-next/src/build/patch/patches/patchBackgroundRevalidation.ts, packages/open-next/src/build/patch/patches/patchEnvVar.ts, packages/open-next/src/build/patch/patches/patchFetchCacheISR.ts, packages/open-next/src/build/patch/patches/patchFetchCacheWaitUntil.ts, packages/open-next/src/build/patch/patches/patchNextServer.ts, packages/open-next/src/plugins/content-updater.ts, packages/tests-unit/tests/build/patch/codePatcher.test.ts
Remove the `VersionedField` in favor of an optional `versions` field on a patch.
--
There are 2 ways to patch the code in aws/cloudflare:
- the `CodePatcher` is used to patch the files before the build
- the `ContentUpdater` is used to patch the files within an ESBuild build
They are similar but do not have feature parity.
The Cf adapter mostly uses the `ContentUpdater` but does not really use the version range for now.
With the recent release of 15.4, the need to apply different patches according to the Next version is becoming more important.
What I'd like to do with this PR (and some follow up PRs) is to unify the 2 mechanisms.
Next steps:
- The version range is pretty limited, I'd like to introduce a predicate in addition to the current string to allow for more flexibiliy, i.e. using …
=> refactor the code patcher

.changeset/pretty-dodos-end.md, packages/open-next/src/core/requestHandler.ts
This fixes https://github.com/opennextjs/opennextjs-aws/issues/936
Upgrading to Next 15.4.4 broke our site but no alerts went off because the response returned a 200 versus a 500. We've reverted and pinned 15.3.5, but we still want the response to be correct.
=> return res.statusCode on "Server failed to respond."

.changeset/olive-buttons-allow.md, packages/open-next/src/adapters/middleware.ts, packages/open-next/src/core/requestHandler.ts, packages/open-next/src/core/routing/middleware.ts, packages/open-next/src/core/routing/util.ts, packages/open-next/src/core/routingHandler.ts, packages/open-next/src/http/openNextResponse.ts, packages/open-next/src/types/open-next.ts
For #924
Tested on both AWS and Cloudflare adapter. It should now propogate the status code from rewrites happening in the middleware to the final response.
=> fix: Propogate the status code in middleware rewrites

.changeset/fair-pillows-yawn.md, packages/open-next/src/overrides/wrappers/express-dev.ts
Discussed in [#686](https://github.com/opennextjs/opennextjs-cloudflare/issues/686) over at `opennextjs-cloudflare`
`next-auth` and possibly more libraries rely on the `x-forwarded-proto` header to be `http` to work out of the box when run locally. In `next start` or `next dev` they set this to `http` when ran locally. 
To make `opennextjs-cloudflarejs preview` and our node converter when running OpenNext locally behave the same we would want to set this header to `http`. This would make the user not have to set an [`AUTH_URL`](https://authjs.dev/getting-started/deployment#auth_url) in those modes.
=> fix(converters): Ensure x-forwarded-proto is set to http when running locally

.changeset/rich-pumas-shop.md, packages/open-next/src/adapters/cache.ts, packages/open-next/src/adapters/composable-cache.ts, packages/open-next/src/types/overrides.ts, packages/tests-unit/tests/adapters/cache.test.ts
Introduce a new option to bypass tag cache validation from the incremental caches, along with unit tests to ensure expected behavior.
This is useful in 2 situations: 
- When you don't need the tag cache only for some routes/data cache entry
- When you're sure that a route has not been revalidated. For example in cloudflare when a cache entry is coming from the cache api and that you have automatic cache invalidation.
=> Add shouldBypassTagCache option for incremental caches

.changeset/wet-emus-brake.md, packages/open-next/src/adapters/composable-cache.ts, packages/tests-unit/tests/adapters/composable-cache.test.ts
Update handling of pending writes to prevent locked readable streams in the composable cache. This change improves the management of cache entries and ensures proper stream handling.
~~I want to make some test first, as this one will increase memory usage, which could be an issue in cloudflare~~
Seems to be working fine
=> Fix locked readable stream in composable cache

.changeset/soft-queens-sing.md, packages/open-next/src/build.ts
This PR fixes the bug where subsequent builds would cause the `.open-next` output directory to be recursively bundled within itself, leading to exponential growth in bundle size and slow build times.
I used OpenNext to build my Nextjs app with Prisma a couple times until I got an error:
```
Failed to compile.
Error: ENAMETOOLONG: name too long, readlink 
.open-next/server-functions/default/apps/[app-name]/.open-next/server-functions/default/apps/[app-name]/.open-next/server-functions/default/apps/[app-name]/.open-next/server-functions/default/apps/[app-name]/.open-next/server-functions/default/apps/[app-name]/.open-next/server-functions/default/apps/[app-name]/.open-next/server-functions/default/apps/[app-name]/.open-next/server-functions/default/apps/[app-name]/.open-next/server-functions …
```
=> Clean output directory before build to prevent recursive bundling

.changeset/perfect-jeans-divide.md, packages/open-next/src/core/routing/cacheInterceptor.ts, packages/tests-unit/tests/core/routing/cacheInterceptor.test.ts
Introduce support for handling binary content types in the cache interceptor, along with tests for route type retrieval from the cache.
=> Add binary content type handling in cache interceptor

.changeset/eleven-moose-heal.md, packages/open-next/src/http/openNextResponse.ts, packages/open-next/src/overrides/wrappers/cloudflare-node.ts, packages/open-next/src/overrides/wrappers/express-dev.ts, packages/open-next/src/overrides/wrappers/node.ts, packages/open-next/src/types/open-next.ts
To make `request.signal.onabort` work in route handlers. Currently only works for `cloudflare-node`, `node` and `express-dev`. It will close the `OpenNextNodeResponse` we pass into `NextServer`'s request handler when the original response in the wrapper is closed. This will ensure that the AbortSignal associated with `request.signal` is properly triggered when a client disconnects during a streaming response.
I did try to get it to work with `awsLambda.streamifyResponse`. It looks like we get no event emitted on `responseStream` when a client disconnects. I even tried with a barebone Lambda like this:
```ts
exports.handler = awslambda.streamifyResponse(
async (event, responseStream, context) => {
responseStream.setContentType('text/event-stream')
responseStream.on("close", ()=> {
// this …
```
=> fix: Add automatic response cleanup via AbortSignal

.changeset/tame-seas-raise.md, examples/app-router/app/api/isr/route.ts, packages/open-next/src/overrides/wrappers/express-dev.ts
For #958 
This is to make the E2E work when ran locally.
=> fix(express-dev): Disable x-powered-by header

.changeset/long-ears-worry.md, packages/open-next/src/build/createImageOptimizationBundle.ts
This is the only thing we need I think to make it work locally. By not specifying an `arch`, `npm install` command will choose it for us. (i.e our system one)
=> fix(dev-overrides): Make Image optimization work locally

.changeset/popular-tomatoes-jog.md, packages/open-next/src/build/createAssets.ts, packages/open-next/src/utils/safe-json-parse.ts
MR closes https://github.com/opennextjs/opennextjs-aws/issues/961
=> fix: createAssets fails in case of broken JSON in fetch cache

.changeset/lovely-goats-rest.md, packages/open-next/src/build/edge/createEdgeBundle.ts
If you have `enableCacheInterception` enabled `includeCache` will be true there, meaning `esbuild` will potentially bundle `aws4fetch` and the fallback overrides(`sqs-lite`, `dynamodb-lite` & `s3-lite`) in the middleware handler file. This can happen if you build from the Cloudflare adapter cause the `overrides` can contain anonymous functions and the `override` function would return `undefined`.
To see this your self, build the `examples/e2e/app-router` in cloudflare repo and look for `aws4fetch`, `sqs-lite` etc.. in the middleware handler file. Do we really need to pass any values [here](https://github.com/sommeeeer/opennextjs-aws/blob/0e962f1a006449df2d7444ed021a9b6b9a287fd2/packages/open-next/src/build/edge/createEdgeBundle.ts#L86-L91) tho? I can't find any of them bundled in the …
=> fix(build): Refactor fallback values to be dummy overrides in createEdgeBundle

.changeset/gold-penguins-walk.md, packages/open-next/src/core/routing/cacheInterceptor.ts, packages/tests-unit/tests/core/routing/cacheInterceptor.test.ts
`shouldBypassTagCache` was implemented in https://github.com/opennextjs/opennextjs-aws/pull/944.
It is useful to bypass the Tag Cache when we know that an entry has not been revalidated.
The original PR missed an updated in the cache interceptor resulting in the Tag Cache never being bypassed when it is in use.
/cc @dario-piotrowicz
=> fix: allow bypassing the Tag Cache in the interceptor

.changeset/tiny-points-fry.md, packages/open-next/src/build/copyTracedFiles.ts, packages/open-next/src/build/installDeps.ts, packages/tests-unit/tests/build/copyTracedFiles.test.ts
When you use `pnpm` there will be a symbolic link pointing to the store. Our current regex didn't exclude this as it was just looking for all the files living under a folder. This could cause `file already exists` errors when trying to install `sharp` or any of the other excluded packages on the default server function.
```bash
❯ cd node_modules
❯ file sharp
sharp: symbolic link to .pnpm/sharp@0.34.3/node_modules/sharp
```
Reference: Discord [thread](https://discord.com/channels/1283128968140161065/1353461350680101015)
=> fix(build): Improve regex in copy traced files to skip symbolic links

.changeset/shiny-plants-remember.md, examples/app-router/app/headers/execution-order/page.tsx, examples/app-router/middleware.ts, examples/app-router/open-next.config.local.ts, examples/app-router/open-next.config.ts, packages/open-next/src/core/routingHandler.ts, packages/open-next/src/types/open-next.ts, packages/tests-e2e/tests/appRouter/headers.test.ts
Fixes opennextjs/opennextjs-aws#973
I'm not sure if the added configuration option should be under `dangerous`, but just put it there since it changes some behavior. Also alternative names are welcome :) 
Should I also create a PR to the docs repo, or is that auto-synced based on types / comment extraction?
=> feat: add option to align header priorization execution order

.changeset/rude-trains-know.md, packages/open-next/src/utils/cache.ts, packages/tests-unit/tests/adapters/cache.test.ts
Before this PR `hasBeenRevalidated` might be called with an empty tag list.
However we can early return `false` in this case
=> fix: bypass next tag cache when there are no tags to check

.changeset/seven-ducks-breathe.md, packages/open-next/src/http/util.ts, packages/tests-unit/tests/http/utils.test.ts
This is for https://github.com/opennextjs/opennextjs-cloudflare/issues/875#issuecomment-3258248276
Next will return a header like `Location: ["/target", "/target"];` on the response for a `redirect("/target");` in a static `page.tsx` when you dont have an `incrementalCache`. We should not merge that header's value with `join(",");` 
Affected line in Next: https://github.com/vercel/next.js/blob/ea08bf27/packages/next/src/server/base-server.ts#L1521
This is me `console.log(res._res.headers)` before and after that line with a reproduction:
=> fix: Avoid merging Location header on response when its an array
